select ROWID,t.* from GENERICO.TIPO_IMAGEM_EQUIPAMENTO t
ORDER BY 2 DESC;


SELECT *
 FROM GENERICO.ORDEM_SERVICO_TIPO_EMPRESTIMO OSTE
 ORDER BY 1 DESC
 FOR UPDATE; 

select * from GENERICO.BEM_PATRIMONIAL_TP_IMAGEM_EQUI t
where t.seq_tipo_imagem_equipamento = 5;


