
SELECT 0 AS ORDEM, -1 COD_TIPO_PATRIMONIO, 'TODOS' DSC_TIPO_PATRIMONIO

FROM DUAL

UNION

SELECT 1 AS ORDEM, TP.COD_TIPO_PATRIMONIO, TP.DSC_TIPO_PATRIMONIO

FROM TIPO_PATRIMONIO TP,

     USUARIO_TIPO_PATRIMONIO UTP,

     INSTITUICAO_TIPO_PATRIMONIO ITP

WHERE UTP.COD_TIPO_PATRIMONIO = TP.COD_TIPO_PATRIMONIO

  --AND UTP.NUM_USER_BANCO = 66827
   AND UTP.NUM_USER_BANCO = 3787

  AND ITP.COD_TIPO_PATRIMONIO = TP.COD_TIPO_PATRIMONIO

  AND ITP.COD_INST_SISTEMA = 1

ORDER BY 1, 3;
-------------------------------------------------------
SELECT CC.COD_CENCUSTO,
       CC.COD_CENCUSTO || ' - ' || CC.NOM_CENCUSTO CEN_CUSTO,
       i.nom_instituto
  FROM CENTRO_CUSTO CC, CENTRO_CUSTO_USUARIO U, INSTITUTO I
 WHERE U.NUM_USER_BANCO = 58127--FC_NUM_USER_BANCO
   AND U.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
   AND I.COD_INST_SISTEMA = 1
   AND i.cod_instituto = 1
   AND CC.IDF_ATIVO = 'S'
UNION
SELECT CC.COD_CENCUSTO,
       CC.COD_CENCUSTO || ' - ' || CC.NOM_CENCUSTO CEN_CUSTO
       ,i.nom_instituto
  FROM CENTRO_CUSTO CC, CENTRO_CUSTO_USUARIO_PERMISSAO U, INSTITUTO I
 WHERE U.NUM_USER_BANCO = 58127--FC_NUM_USER_BANCO
   AND U.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
   AND I.COD_INST_SISTEMA = 1
   AND i.cod_instituto = 1
   AND CC.IDF_ATIVO = 'S'
   AND U.IDF_ATIVO = 0
 ORDER BY CEN_CUSTO;
 -----------------------------------------------------
SELECT x.cod_cencusto FROM (SELECT CC.COD_CENCUSTO,
       CC.COD_CENCUSTO || ' - ' || CC.NOM_CENCUSTO CEN_CUSTO,
       i.nom_instituto
  FROM CENTRO_CUSTO CC, CENTRO_CUSTO_USUARIO U, INSTITUTO I
 WHERE U.NUM_USER_BANCO = FC_NUM_USER_BANCO
   AND U.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
   AND I.COD_INST_SISTEMA = 1
   AND i.cod_instituto = 1
   AND CC.IDF_ATIVO = 'S'
UNION
SELECT CC.COD_CENCUSTO,
       CC.COD_CENCUSTO || ' - ' || CC.NOM_CENCUSTO CEN_CUSTO
       ,i.nom_instituto
  FROM CENTRO_CUSTO CC, CENTRO_CUSTO_USUARIO_PERMISSAO U, INSTITUTO I
 WHERE U.NUM_USER_BANCO = FC_NUM_USER_BANCO
   AND U.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
   AND I.COD_INST_SISTEMA = 1
   AND i.cod_instituto = 1
   AND CC.IDF_ATIVO = 'S'
   AND U.IDF_ATIVO = 0
 ORDER BY CEN_CUSTO) x
 WHERE NOT EXISTS
 (
   SELECT y.cod_cencusto FROM (SELECT CC.COD_CENCUSTO,
       CC.COD_CENCUSTO || ' - ' || CC.NOM_CENCUSTO CEN_CUSTO,
       i.nom_instituto
  FROM CENTRO_CUSTO CC, CENTRO_CUSTO_USUARIO U, INSTITUTO I
 WHERE U.NUM_USER_BANCO = 3787
   AND U.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
   AND I.COD_INST_SISTEMA = 1
   AND i.cod_instituto = 1
   AND CC.IDF_ATIVO = 'S'
UNION
SELECT CC.COD_CENCUSTO,
       CC.COD_CENCUSTO || ' - ' || CC.NOM_CENCUSTO CEN_CUSTO
       ,i.nom_instituto
  FROM CENTRO_CUSTO CC, CENTRO_CUSTO_USUARIO_PERMISSAO U, INSTITUTO I
 WHERE U.NUM_USER_BANCO = 3787
   AND U.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
   AND I.COD_INST_SISTEMA = 1
   AND i.cod_instituto = 1
   AND CC.IDF_ATIVO = 'S'
   AND U.IDF_ATIVO = 0
 ORDER BY CEN_CUSTO) y
 WHERE y.cod_cencusto = x.cod_cencusto
 );
-------------------------------------------------------
-- VCLOBO: 58127
--KRCOCENZA: 3787
SELECT *
 FROM usuario u
 WHERE UPPER(u.nom_usuario_banco) = 'KRCOCENZA';
