-- Create tables

-- TABELA CENTRALIZADA COM TODOS OS ANEXOS NECESSÁRIOS NOS SISTEMAS
create table GENERICO.ANEXO_SISTEMA
(
  SEQ_ANEXO_SISTEMA     NUMBER NOT NULL,
  CTU_ARQUIVO           BLOB NULL,
  DSC_LINK_EXTERNO      VARCHAR2(4000) NULL
  DSC_NOME_ARQUIVO      VARCHAR2(255) NOT NULL,
  DSC_COMPLEMENTO       VARCHAR2(4000) NULL 
  NUM_USER_CADASTRO     NUMBER NOT NULL,
  DTA_HOR_CADASTRO      DATE DEFAULT SYSDATE NOT NULL,
  DTA_EXCLUSAO_LOGICA   DATE NULL,
  NUM_USUARIO_EXCLUSAO  NUMBER NULL
);

ALTER TABLE GENERICO.ANEXO_SISTEMA ADD CONSTRAINT PK_ANEXO_SISTEMA PRIMARY KEY (SEQ_ANEXO_SISTEMA);
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.SEQ_ANEXO_SISTEMA is 'CHAVE ATRIBUIDA VIA SEQUENCE';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.CTU_ARQUIVO is 'CONTEÚDO DO ARQUIVO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.DSC_LINK_EXTERNO is 'URL QUANDO O ARQUIVO FOR ACESSADO POR REFERENCI EXTERNA';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.DSC_NOME_ARQUIVO is 'NOME COMPLETO DO ARQUIVO COM EXTENSÃO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.DSC_COMPLEMENTO is 'DESCRIÇÃO COMPLEMENTAR SOBRE O ARQUIVO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.NUM_USER_CADASTRO is 'USUÁRIO QUE INCLUIU O ANEXO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.DTA_HOR_CADASTRO is 'DATA DO ORACLE INSERIDO VIA SYSDATE DEFAULT NO MOMENTO DA INCLUSÃO DO REGISTRO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.NUM_USUARIO_EXCLUSAO is 'USUÁRIO QUE EXCLUIU LOGICAMENTE O ANEXO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA.DTA_EXCLUSAO_LOGICA is 'DATA DA EXCLUSÃO LÓGICA REGISTRADO VIA TRIGGER';



-- OBJETOS ENCADEADOS HIERARQUICAMENTE PARA CONFIGURAR A ORGANIZAÇÃO E DEFINIR AS REGRAS DE VÍNCULO DOS ANEXOS
-- OS OBJETOS PODEM REPRESENTAR SISTEMAS, MÓDULOS E OUTROS OBJETOS
table GENERICO.ANEXO_SISTEMA_OBJETO
(
  SEQ_ANEXO_SISTEMA_OBJETO      NUMBER NOT NULL,
  DSC_OBJETO                    VARCHAR2(50) NOT NULL,
  DSC_REGRA_CHAVE               VARCHAR2(30) NULL,
  SEQ_ANEXO_SISTEMA_OBJ_PAI     NUMBER NULL
);

ALTER TABLE GENERICO.ANEXO_SISTEMA_OBJETO ADD CONSTRAINT PK_SEQ_ANEXO_SISTEMA_OBJETO PRIMARY KEY (SEQ_ANEXO_SISTEMA_OBJETO);
ALTER TABLE GENERICO.ANEXO_SISTEMA_OBJETO ADD CONSTRAINT FK_ANEXO_SISTEMA_OBJ_PAI FOREIGN KEY (SEQ_ANEXO_HC_OBJETO_PAI) REFERENCES GENERICO.ANEXO_SISTEMA_OBJETO (SEQ_ANEXO_SISTEMA_OBJETO);
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_OBJETO.SEQ_ANEXO_SISTEMA_OBJETO is 'CHAVE ATRIBUIDA VIA SEQUENCE';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_OBJETO.DSC_OBJETO is 'DESCRIÇÃO DO OBJETO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_OBJETO.DSC_REGRA_CHAVE is 'DESCRIÇÃO DA REGRA DE COMO A CHAVE SERÁ GRAVADA NA TABELA ANEXO_SISTEMA_VINCULO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_OBJETO.SEQ_ANEXO_SISTEMA_OBJ_PAI is 'AUTO RELACIONAMENTO PARA ORGANIZAÇÃO HIERARQUICA DOS OBJETOS';

-- VINCULO DOS ANEXOS COM OS OBJETOS 
create table GENERICO.ANEXO_SISTEMA_VINCULO
(
  SEQ_ANEXO_SISTEMA          NUMBER NOT NULL,
  SEQ_ANEXO_SISTEMA_OBJETO   NUMBER NOT NULL,
  DSC_CHAVE                  VARCHAR2(20) NOT NULL
);

ALTER TABLE GENERICO.ANEXO_SISTEMA_VINCULO ADD CONSTRAINT PK_ANEXO_HC_VINCULO PRIMARY KEY (SEQ_ANEXO_SISTEMA, SEQ_ANEXO_HC_OBJETO);
ALTER TABLE GENERICO.ANEXO_SISTEMA_VINCULO ADD CONSTRAINT FK_ANEXO_SIST_VINCULO FOREIGN KEY (SEQ_ANEXO_SISTEMA) REFERENCES GENERICO.ANEXO_SISTEMA (SEQ_ANEXO_SISTEMA);
ALTER TABLE GENERICO.ANEXO_SISTEMA_VINCULO ADD CONSTRAINT FK_ANEXO_SIST_OBJ_VINCULO FOREIGN KEY (SEQ_ANEXO_SISTEMA_OBJETO) REFERENCES GENERICO.ANEXO_HC_OBJETO (SEQ_ANEXO_SISTEMA_OBJETO);
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_VINCULO.SEQ_ANEXO_SISTEMA is 'REFERÊNCIA À CHAVE DA TABELA ANEXO_SISTEMA';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_VINCULO.SEQ_ANEXO_SISTEMA_OBJETO is 'REFERÊNCIA À CHAVE DA TABELA ANEXO_SISTEMA_OBJETO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_VINCULO.DSC_CHAVE is 'CHAVE DA TABELA VINCULADA CONFORME DESCRITO NA REGRA DA TABELA ANEXO_SISTEMA_OBJETO';


-- TABELA DE LOG DOS VÍNCULOS
create table GENERICO.ANEXO_SISTEMA_LOG
(
  SEQ_ANEXO_SISTEMA         NUMBER NOT NULL,
  SEQ_ANEXO_SISTEMA_OBJETO  NUMBER NOT NULL,
  IDF_OPERAÇÃO              VARCHAR2(1) NOT NULL,
  DTA_HOR_LOG               DATE DEFAULT SYSDATE NOT NULL,
  NUM_USER_LOG              NUMBER NOT NULL
);

COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_LOG.SEQ_ANEXO_SISTEMA is 'REFERÊNCIA À CHAVE DA TABELA ANEXO_SISTEMA';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_LOG.SEQ_ANEXO_SISTEMA_OBJETO is 'REFERÊNCIA À CHAVE DA TABELA ANEXO_SISTEMA_OBJETO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_LOG.IDF_OPERAÇÃO is 'I - INCLUSÃO |  E - EXCLUSÃO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_LOG.DTA_HOR_LOG is 'DATA DA OPERAÇÃO';
COMMENT ON COLUMN GENERICO.ANEXO_SISTEMA_LOG.NUM_USER_LOG is 'USUÁRIO DA OPERAÇÃO';


---------------------------------------------------
--Create Triggers

CREATE OR REPLACE TRIGGER ESTOQUE.TG_AI_ANEXO_SISTEMA_VINCULO
  AFTER INSERT
  ON GENERICO.ANEXO_SISTEMA_VINCULO
  FOR EACH ROW
BEGIN
   INSERT INTO GENERICO.ANEXO_SISTEMA_LOG(SEQ_ANEXO_SISTEMA, SEQ_ANEXO_SISTEMA_OBJETO, IDF_OPERAÇÃO , NUM_USER_LOG)
  VALUES(:NEW.SEQ_ANEXO_SISTEMA, :NEW.SEQ_ANEXO_SISTEMA_OBJETO,'I', fc_num_user_banco);
END TG_BD_ANEXO_SISTEMA_VINCULO;

CREATE OR REPLACE TRIGGER ESTOQUE.TG_BD_ANEXO_SISTEMA_VINCULO
  BEFORE DELETE
  ON GENERICO.ANEXO_SISTEMA_VINCULO
  FOR EACH ROW
BEGIN
   INSERT INTO GENERICO.ANEXO_SISTEMA_LOG(SEQ_ANEXO_SISTEMA, SEQ_ANEXO_SISTEMA_OBJETO, IDF_OPERAÇÃO , NUM_USER_LOG)
  VALUES(:OLD.SEQ_ANEXO_SISTEMA, :OLD.SEQ_ANEXO_SISTEMA_OBJETO,'E', fc_num_user_banco);
END TG_BD_ANEXO_SISTEMA_VINCULO;

-------------------------------------------------------------------------------------------
