SELECT ROWNUM, TRIM(OS.NUM_ORDEM_SERVICO || '/' || OS.ANO_ORDEM_SERVICO) NUM_OS,
       OS.NUM_ORDEM_SERVICO,
       OS.ANO_ORDEM_SERVICO,
       OS.NUM_ORDEM,
       OS.IDF_PRIORIZADO,
       DECODE(OS.IDF_PRIORIZADO,1,'ALTA',2,'MEDIA',3,'BAIXA') CRITICIDADE,
       OS.DSC_SERVICO,
       OS.NUM_BEM,
       OS.NUM_MAN_PREVENTIVA,
       OS.COD_UNIDADE_EXECUTANTE,
       TROS1.NUM_TRIAGEM_OS,
       TROS1.DTA_HOR_FIM_TRIAGEM,
       TROS1.COD_CLASSIFICACAO_OS,
       COS1.DSC_CLASSIFICACAO_OS DSC_CLASSIF_ORD,
       FOS1.SEQ_FUNC_ORDEM_SERVICO,
       CASE WHEN 1 = 50 THEN OS.IDF_PRIORIZADO ELSE FOS1.ORD_EXECUCAO END ORD_EXECUCAO,
       FOS1.NUM_FUNC_UNIDADE,
       FOS1.DTA_HOR_FINALIZACAO,
       FOS1.DTA_HOR_TRIAGEM,
       FOS1.DTA_PREV_CONCLUSAO,
       FOS1.SEQ_TAREFA_ORDEM_SERVICO,
       S3.SEQ_APONTAMENTO_ATIVIDADE,
       S3.COD_ATIVIDADE_HC,
       S3.CPL_ATIVIDADE,
       S3.TOT_HOR_DIA R_TOT_HOR_DIA,
       LPAD(S3.HOR_DIA,2,'0') || ':' || LPAD(TO_CHAR(S3.MIN_DIA,'FM99'),2,'0') S_TOT_HOR_DIA,
       S3.TOT_HOR_APONTADAS R_TOT_HOR_APONTADAS,
       SUBSTR(LPAD(S3.HOR_APONTADA,DECODE(LENGTH(S3.HOR_APONTADA),1,2,LENGTH(S3.HOR_APONTADA)),'0') || ':' || LPAD(TO_CHAR(S3.MIN_APONTADA,'FM99'),2,'0'),1,10) S_TOT_HOR_APONTADAS,
       S3.DTA_HOR_INICIO_ATIVIDADE,
       DECODE(OS.DSC_TITULO_OS,NULL,SUBSTR(OS.DSC_SERVICO,1,255),OS.DSC_TITULO_OS) DSC_REDUZIDA_SERVICO,
       DECODE((SELECT COUNT(*)
                 FROM OBSERVACAO_TRIAGEM_OS OBS
                 WHERE OBS.NUM_ORDEM = OS.NUM_ORDEM),0,'NÃO','SIM') OBS,
       DECODE(NP.NUM_PATRIMONIO, Null, 'S/N', NP.NUM_PATRIMONIO) NUM_PATRIMONIO,
       CASE WHEN L.COD_INST_SISTEMA = 50 THEN CC.NOM_CENCUSTO|| '-' ||OS.COD_CENCUSTO ELSE L.NOM_LOCAL END NOM_LOCAL,
       U.NOM_USUARIO || ' ' || U.SBN_USUARIO NOME_USUARIO
       , OS.CPL_LOCAL, SUBSTR(OS.DSC_TECNICA_SERVICO,1,250) DSC_TECNICA_SERVICO

  FROM ORDEM_SERVICO OS,
       TRIAGEM_ORDEM_SERVICO TROS1,
       FUNCIONARIO_ORDEM_SERVICO FOS1,
       NUMERO_PATRIMONIO NP,
       BEM_PATRIMONIAL BP,
       CLASSIFICACAO_OS COS1,
       LOCAL L,
       USUARIO U,
       CENTRO_CUSTO CC,

       (SELECT S2.SEQ_FUNC_ORDEM_SERVICO,
               S2.NUM_TRIAGEM_OS,
               S2.NUM_FUNC_UNIDADE,
               AA2.SEQ_APONTAMENTO_ATIVIDADE,
               AA2.COD_ATIVIDADE_HC,
               AA2.DTA_HOR_INICIO_ATIVIDADE,
               AA2.CPL_ATIVIDADE,
               S2.TOT_HOR_APONTADAS,
               TRUNC(NVL(S2.TOT_HOR_APONTADAS,0)) HOR_APONTADA,
               ((NVL(S2.TOT_HOR_APONTADAS,0)) - TRUNC(NVL(S2.TOT_HOR_APONTADAS,0))) * 60 MIN_APONTADA,
               NVL(AA2.DTA_HOR_FIM_ATIVIDADE-AA2.DTA_HOR_INICIO_ATIVIDADE,0) * 24 TOT_HOR_DIA,
               TRUNC(NVL(AA2.DTA_HOR_FIM_ATIVIDADE-AA2.DTA_HOR_INICIO_ATIVIDADE,0) * 24) HOR_DIA,

               ((NVL(AA2.DTA_HOR_FIM_ATIVIDADE-AA2.DTA_HOR_INICIO_ATIVIDADE,0) * 24) - TRUNC(NVL(AA2.DTA_HOR_FIM_ATIVIDADE-AA2.DTA_HOR_INICIO_ATIVIDADE,0) * 24)) * 60 MIN_DIA

          FROM APONTAMENTO_ATIVIDADE AA2,
               (SELECT S1.SEQ_FUNC_ORDEM_SERVICO,
                       S1.NUM_TRIAGEM_OS,
                       S1.NUM_FUNC_UNIDADE,

                       (NVL(SUM((SELECT SUM(AA1.DTA_HOR_FIM_ATIVIDADE - AA1.DTA_HOR_INICIO_ATIVIDADE)
                                  FROM APONTAMENTO_ATIVIDADE AA1
                                 WHERE AA1.SEQ_FUNC_ORDEM_SERVICO = S1.SEQ_FUNC_ORDEM_SERVICO)),0) +

                       NVL(SUM((SELECT SUM(AA1.DTA_HOR_FIM_ATIVIDADE - AA1.DTA_HOR_INICIO_ATIVIDADE)
                                  FROM APONTAMENTO_ATIVIDADE AA1
                                 WHERE AA1.SEQ_FUNC_ORDEM_SERVICO IS NULL
                                   AND AA1.NUM_TRIAGEM_OS = S1.NUM_TRIAGEM_OS
                                   AND AA1.NUM_FUNC_UNIDADE = S1.NUM_FUNC_UNIDADE)),0)) * 24 TOT_HOR_APONTADAS

                  FROM (SELECT FOS.SEQ_FUNC_ORDEM_SERVICO,
                               FOS.NUM_TRIAGEM_OS,
                               FOS.NUM_FUNC_UNIDADE
                          FROM FUNCIONARIO_ORDEM_SERVICO FOS, 
                               TRIAGEM_ORDEM_SERVICO TROS

                         WHERE FOS.NUM_FUNC_UNIDADE = 4597
                           AND TROS.COD_UNIDADE_EXECUTANTE = 220
                           AND TROS.DTA_HOR_FIM_TRIAGEM = TO_DATE('01/01/1800', 'DD/MM/YYYY')
                           AND FOS.DTA_HOR_FINALIZACAO = TO_DATE('01/01/1800', 'DD/MM/YYYY')
                           AND FOS.NUM_TRIAGEM_OS = TROS.NUM_TRIAGEM_OS

                        UNION

                        SELECT AA.SEQ_FUNC_ORDEM_SERVICO,
                               AA.NUM_TRIAGEM_OS,
                               AA.NUM_FUNC_UNIDADE
                          FROM APONTAMENTO_ATIVIDADE AA

                         WHERE AA.NUM_FUNC_UNIDADE = 4597
                           AND AA.DTA_HOR_INICIO_ATIVIDADE BETWEEN
                               TO_DATE('28/03/2022', 'DD/MM/YYYY') AND TO_DATE('28/03/2022' , 'DD/MM/YYYY HH24:MI:SS')) S1

                GROUP BY S1.SEQ_FUNC_ORDEM_SERVICO,
                         S1.NUM_TRIAGEM_OS,
                         S1.NUM_FUNC_UNIDADE) S2

         WHERE S2.SEQ_FUNC_ORDEM_SERVICO = AA2.SEQ_FUNC_ORDEM_SERVICO(+)

           AND AA2.DTA_HOR_INICIO_ATIVIDADE(+) BETWEEN TO_DATE('28/03/2022', 'DD/MM/YYYY')     AND TO_DATE('28/03/2022' , 'DD/MM/YYYY') )S3

 WHERE OS.COD_SITUACAO_OS = 3
   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO
   AND OS.NUM_ORDEM = TROS1.NUM_ORDEM
   AND TROS1.NUM_TRIAGEM_OS = FOS1.NUM_TRIAGEM_OS
   AND FOS1.SEQ_FUNC_ORDEM_SERVICO = S3.SEQ_FUNC_ORDEM_SERVICO
   AND OS.NUM_BEM = BP.NUM_BEM(+)
   AND BP.NUM_BEM = NP.NUM_BEM(+)
   AND BP.COD_TIPO_PATRIMONIO = NP.COD_TIPO_PATRIMONIO(+)
   AND OS.COD_LOCAL = L.COD_LOCAL(+)
   AND TROS1.COD_CLASSIFICACAO_OS = COS1.COD_CLASSIFICACAO_OS(+)
   AND OS.NUM_USER_BANCO = U.NUM_USER_BANCO
ORDER BY NUM_ORDEM DESC;
