  SELECT p.dta_nascimento,
        FNC_CALCULA_TEMPO(SYSDATE,  p.dta_nascimento, 'aammdd') IDADE
    FROM Paciente_Sem_Registro_Hc p
    WHERE 1 = 1
   -- AND p.nom_paciente LIKE '%%'
    AND p.cod_paciente_sem_registro_hc = 2368591;
    
    SELECT *
     FROM tipo_vacina tv
     WHERE tv.cod_tipo_vacina = 71;
     
     select * from GENERICO.VACINA_CONFIGURACAO t
where t.cod_tipo_vacina = 71;

SELECT *
 FROM vacina_recepcao vr
 WHERE vr.cod_paciente = '1089770D';
 
 SELECT *
  FROM usuario u
  WHERE 1 = 1
  AND U.NOM_USUARIO_BANCO LIKE '%SANDRAR%';
  --AND u.nom_usuario LIKE '%SANDRA RODRI%';
  -------------------------------------
  --62109
  SELECT TL.COD_TIPO_LANCAMENTO, DSC_TIPO_LANCAMENTO,
               NVL(SUBSTR(FC_TIPO_LANCAMENTO_DSC(TL.COD_TIPO_LANCAMENTO,0),1,250),DSC_TIPO_LANCAMENTO) TIPO_LANCAMENTO
FROM TIPO_LANCAMENTO TL
WHERE IDF_RECEITA_DESPESA=NVL(:RECEITA_DESPESA,IDF_RECEITA_DESPESA)
ORDER BY TIPO_LANCAMENTO;

SELECT *
 FROM TIPO_LANCAMENTO TL
 WHERE TL.COD_TIPO_LANCAMENTO = 133;
 
 
 SELECT TA.COD_TIPO_AQUISICAO, TA.DSC_TIPO_AQUISICAO
FROM USUARIO_TIPO_AQUISICAO UTA, TIPO_AQUISICAO TA
WHERE UTA.NUM_USER_BANCO=FC_NUM_USER_BANCO
  AND UTA.COD_TIPO_AQUISICAO=TA.COD_TIPO_AQUISICAO
  AND UTA.COD_SISTEMA = 72
ORDER BY DSC_TIPO_AQUISICAO;
