select * from GENERICO.ITENS_LISTA_CONTROLE t
where 1 = 1
AND t.seq_lista_controle = 33
AND T.COD_MATERIAL = '03040410' ;

SELECT *
 FROM REPOSITORIO_LISTA_CONTROLE RLC
 WHERE RLC.DSC_IDENTIFICACAO LIKE '%PEDIATRIA%'
 AND RLC.SEQ_LISTA_CONTROLE = 33;
 
select * from GENERICO.LACRE_REPOSITORIO t
where t.seq_repositorio = 29
ORDER BY 1 DESC;

select t.*, ROWID from GENERICO.LACRE_REPOSITORIO_ITENS t
where t.seq_lacre_repositorio = 56812
AND COD_MATERIAL = '03040410';
