/*Centro de custo bloqueado por OSs pendentes*/
SELECT distinct A.NUM_ORDEM, A.COD_CENCUSTO,  A.COD_UNIDADE_EXECUTANTE, A.DTA_HOR_HISTORICO,
       TRUNC(SYSDATE-A.DTA_HOR_HISTORICO) DTA_HISTORICO 
FROM ORDEM_SERVICO A, PER_CENTRO_CUSTO_USUARIO E, CENTRO_CUSTO_USUARIO_PERMISSAO F, CENTRO_CUSTO CC,
     INSTITUTO I
WHERE F.COD_CENCUSTO = 'CFDB06017'
  AND F.IDF_ATIVO = '0'
  AND F.COD_CENCUSTO = A.COD_CENCUSTO
  AND F.NUM_SEQ_PERMISSAO = E.NUM_SEQ_PERMISSAO
  AND E.COD_PERMISSAO IN (1)
  AND E.IDF_ATIVO = 0
  AND A.COD_SITUACAO_OS = 4
  AND A.IDF_VISUALIZA_APOS_EMAIL = 0
  AND A.COD_CENCUSTO = CC.COD_CENCUSTO
  AND CC.COD_INSTITUTO = I.COD_INSTITUTO
  AND I.COD_INST_SISTEMA = 1
ORDER BY DTA_HOR_HISTORICO;

SELECT *
 FROM ORDEM_SERVICO OS
 WHERE num_ordem in (1167790, 1170683, 1170623, 1170089);
 FOR UPDATE;--, 1167790, 1170683, 1170623, 1170089);

