 SELECT 
    RLC.SEQ_REPOSITORIO, 
    RLC.DSC_IDENTIFICACAO, 
    RLC.SEQ_LISTA_CONTROLE, 
    RLC.SEQ_TIP_REPOSIT_LST_CONTROL, 
    RLC.DTA_CADASTRO, 
    RLC.DTA_ULTIMA_ALTERACAO, 
    RLC.NUM_USER_CADASTRO, 
    RLC.NUM_USER_ULTIMA_ALTERACAO, 
    RLC.IDF_ATIVO, 
    RLC.NUM_BEM, 
    TIPOREPOSIT.DSC_TIPO_REPOSITORIO, 
    BP.NUM_PATRIMONIO, 
    TIPPATRIMONIO.DSC_TIPO_PATRIMONIO, 
    LS.NOM_LISTA_CONTROLE 
 FROM REPOSITORIO_LISTA_CONTROLE RLC, 
    LISTA_CONTROLE LS, 
    BEM_PATRIMONIAL BP, 
    TIPO_REPOSITORIO_LST_CONTROLE TIPOREPOSIT, 
    TIPO_PATRIMONIO TIPPATRIMONIO 
 WHERE RLC.SEQ_LISTA_CONTROLE = LS.SEQ_LISTA_CONTROLE 
 AND RLC.NUM_BEM = BP.NUM_BEM(+) 
 AND TIPOREPOSIT.SEQ_TIP_REPOSIT_LST_CONTROL = RLC.SEQ_TIP_REPOSIT_LST_CONTROL 
 AND TIPPATRIMONIO.COD_TIPO_PATRIMONIO(+) = BP.COD_TIPO_PATRIMONIO 
 AND LS.COD_INSTITUTO = 1 
 AND RLC.SEQ_TIP_REPOSIT_LST_CONTROL = 1 
 AND RLC.idf_ativo = 'S' 
 order by rlc.dsc_identificacao; 
 
 SELECT *
  FROM USUARIO_ROLE_CENTRO_CUSTO u
  WHERE u.cod_role = 1087
  AND u.cod_inst_sistema = 1;
