SELECT *
 FROM tipo_vacina tv
 FOR UPDATE;
 WHERE tv.idf_ativo = '';
 
 --PENTA INATIVADA ACELULAR 70104384 ML
 --HEXA ACELULAR
 SELECT VC.*
   FROM VACINA_CONFIGURACAO VC
  WHERE 1 = 1
    AND VC.COD_TIPO_VACINA = 71
    AND VC.SEQ_ESTRATEGIA_VACINA = 2
    AND VC.VLR_IDADE_INICIAL <=  '000:02:00'--'036:04:15'
    AND VC.VLR_IDADE_FINAL >= '006:11:29'--'036:04:15'
    AND VC.IDF_ATIVO = 'S'
    AND VC.SEQ_IND_VACINA_MATERIAL IS NULL;
