- Numero de Minutos trabalhados 

 SELECT X.ORD_IMPRESSAO, X.DSC_GRUPO, X.COD_GRUPO, X.NOM_UNIDADE_EXECUTANTE, 

        X.COD_UNIDADE_EXECUTANTE, SUM(QTD_OS_CONCLUIDA) QTD_OS_CONCLUIDA, 

        TO_CHAR(SUM(QTD_HOR_APONT*60),'99999') QTD_MINUTOS, 

        SUM(X.VLR_SERVICO_EXTERNO) VLR_SERVICO_EXTERNO_NUMBER, 

        SUM(X.VLR_MATERIAL) VLR_MATERIAL_NUMBER, 

        SUM(X.VLR_FATURADO) VLR_FATURADO_NUMBER, 

        TO_CHAR(SUM(VLR_SERVICO_EXTERNO),'99999999.99') VLR_SERVICO_EXTERNO, 

        TO_CHAR(SUM(VLR_MATERIAL),'99999999.99') VLR_MATERIAL, 

        TO_CHAR(SUM(VLR_FATURADO),'99999999.99') VLR_FATURADO 

 FROM ( 

 SELECT DISTINCT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO 
NUM_OS, OS.COD_CENCUSTO, 

        TOS.COD_UNIDADE_EXECUTANTE, AA.DTA_HOR_INICIO_ATIVIDADE DTA_OCORRENCIA, 
UE.NOM_UNIDADE_EXECUTANTE, 

        0 QTD_OS_CONCLUIDA, 

        (AA.DTA_HOR_FIM_ATIVIDADE-AA.DTA_HOR_INICIO_ATIVIDADE)*24 QTD_HOR_APONT, 

        0 VLR_SERVICO_EXTERNO, 0 VLR_MATERIAL, 0 VLR_FATURADO, 

        GC.COD_GRUPO, GC.DSC_GRUPO, GC.ORD_IMPRESSAO 

 FROM APONTAMENTO_ATIVIDADE AA, FUNCIONARIO_ORDEM_SERVICO FOS, 

      TRIAGEM_ORDEM_SERVICO TOS, ORDEM_SERVICO OS, CENTRO_CUSTO CC, 
GRUPO_CENCUSTO GC, 

      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE 

       FROM UNIDADE_EXECUTANTE 

       START WITH COD_UNIDADE_EXECUTANTE IN (6,11,70,5,8,22,9,7) 

       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE 

 WHERE AA.DTA_HOR_INICIO_ATIVIDADE BETWEEN TO_DATE('24/08/2021 00:00:00',
'DD/MM/YYYY HH24:MI:SS') AND TO_DATE('24/08/2021 23'24/08/2021 
23:59:59'9'24/08/2021 23:59:59'9','DD/MM/YYYY HH24:MI:SS') +0.9999 

   AND AA.SEQ_FUNC_ORDEM_SERVICO=FOS.SEQ_FUNC_ORDEM_SERVICO 

   AND FOS.NUM_TRIAGEM_OS=TOS.NUM_TRIAGEM_OS 

   AND TOS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE 

   AND TOS.NUM_ORDEM=OS.NUM_ORDEM 

   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO 

   AND CC.COD_GRUPO = GC.COD_GRUPO(+) 

   AND TOS.SEQ_GRUPO_ESTATISTICA = 123 

 UNION ALL 

 -- Numero de OS finalizadas, na oficina que concluiu a OS 

 SELECT DISTINCT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO 
NUM_OS, OS.COD_CENCUSTO, 

        OS.COD_UNIDADE_EXECUTANTE, OS.DTA_HOR_FINALIZACAO DTA_OCORRENCIA, 
UE.NOM_UNIDADE_EXECUTANTE, 

        1 QTD_OS_CONCLUIDA, 0 QTD_HOR_APONT, 0 VLR_SERVICO_EXTERNO, 0 
VLR_MATERIAL, 0 VLR_FATURADO, 

        GC.COD_GRUPO, GC.DSC_GRUPO, GC.ORD_IMPRESSAO 

 FROM ORDEM_SERVICO OS,  CENTRO_CUSTO CC, GRUPO_CENCUSTO GC, 

      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE 

       FROM UNIDADE_EXECUTANTE 

       START WITH COD_UNIDADE_EXECUTANTE IN (6,11,70,5,8,22,9,7) 

       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE 

 WHERE OS.DTA_HOR_FINALIZACAO BETWEEN TO_DATE('24/08/2021 00:00:00',
'DD/MM/YYYY HH24:MI:SS') AND TO_DATE('24/08/2021 23:59:59',
'DD/MM/YYYY HH24:MI:SS') +0.9999 

   AND OS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE 

   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO 

   AND CC.COD_GRUPO = GC.COD_GRUPO(+) 

   AND EXISTS 

     (SELECT TOS.NUM_ORDEM 

      FROM TRIAGEM_ORDEM_SERVICO TOS 

      WHERE TOS.NUM_ORDEM=OS.NUM_ORDEM 

        AND TOS.COD_UNIDADE_EXECUTANTE=OS.COD_UNIDADE_EXECUTANTE 

        AND TOS.SEQ_GRUPO_ESTATISTICA = 123 )

 UNION ALL 

 -- Serviço externo 

 SELECT DISTINCT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO 
NUM_OS, OS.COD_CENCUSTO, 

        TOS.COD_UNIDADE_EXECUTANTE, DF.DTA_EMISSAO DTA_OCORRENCIA, 
UE.NOM_UNIDADE_EXECUTANTE, 

        0 QTD_OS_CONCLUIDA, 

        0 QTD_HOR_APONT, 

        DF.VLR_DOCUMENTO VLR_SERVICO_EXTERNO, 0 VLR_MATERIAL, AGS.VLR_FATURADO, 

        GC.COD_GRUPO, GC.DSC_GRUPO, GC.ORD_IMPRESSAO 

 FROM DOCUMENTO_FINANCEIRO DF, AGENDA_AUT_ENTREGA_SERVICO AGS, 
AUTORIZACAO_ENTREGA_SERVICO AES, COTACAO_PEDIDO_SERVICO CPS, 

      PEDIDO_SERVICO PS, TRIAGEM_ORDEM_SERVICO TOS, ORDEM_SERVICO OS, 

       CENTRO_CUSTO CC, GRUPO_CENCUSTO GC, 

      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE 

       FROM UNIDADE_EXECUTANTE 

       START WITH COD_UNIDADE_EXECUTANTE IN (6,11,70,5,8,22,9,7) 

       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE 

 WHERE DF.DTA_HOR_LANCAMENTO BETWEEN TO_DATE('24/08/2021 00:00:00',
'DD/MM/YYYY HH24:MI:SS') AND TO_DATE('24/08/2021 23:59:59',
'DD/MM/YYYY HH24:MI:SS') +0.9999 

   AND DF.NUM_DOC_FINANCEIRO=AGS.NUM_DOC_FINANCEIRO 

   AND AGS.NUM_AUT_ENTREGA_SERVICO=AES.NUM_AUT_ENTREGA_SERVICO 

   AND AES.NUM_COTACAO_SERVICO=CPS.NUM_COTACAO_SERVICO 

   AND CPS.NUM_PEDIDO_SERVICO=PS.NUM_PEDIDO_SERVICO 

   AND PS.NUM_TRIAGEM_OS=TOS.NUM_TRIAGEM_OS 

   AND TOS.NUM_ORDEM=OS.NUM_ORDEM 

   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO 

   AND CC.COD_GRUPO = GC.COD_GRUPO(+) 

   AND TOS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE 

   AND TOS.SEQ_GRUPO_ESTATISTICA = 123 

 UNION ALL 

  -- Custo dos materiais Gastos, com base no custo médio 

 SELECT DISTINCT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO 
NUM_OS, OS.COD_CENCUSTO, 

        TOS.COD_UNIDADE_EXECUTANTE, IRM.DTA_MOV_CONTABIL DTA_OCORRENCIA, 
UE.NOM_UNIDADE_EXECUTANTE, 

        0 QTD_OS_CONCLUIDA, 0 QTD_HOR_APONT, 0 VLR_SERVICO_EXTERNO, 

        
SUM(IRM.VLR_PONDERADO*IRM.QTD_FORNE_RECEBIDA*DECODE(RM.IDF_TIPO_REQUISICAO,0,1,
1,-1,0)) VLR_MATERIAL, 

        0 VLR_FATURADO, GC.COD_GRUPO, GC.DSC_GRUPO, GC.ORD_IMPRESSAO 

 FROM ITEM_REQUISICAO_MATERIAL IRM, REQUISICAO_MATERIAL RM, 
COMPLEMENTO_REQUISICAO CR, 

      TRIAGEM_ORDEM_SERVICO TOS, ORDEM_SERVICO OS, 

       CENTRO_CUSTO CC, GRUPO_CENCUSTO GC, 

      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE 

       FROM UNIDADE_EXECUTANTE 

       START WITH COD_UNIDADE_EXECUTANTE IN (6,11,70,5,8,22,9,7) 

       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE 

 WHERE IRM.DTA_MOV_CONTABIL BETWEEN TO_DATE('24/08/2021','DD/MM/YYYY') AND TO_DATE('24/08/2021','DD/MM/YYYY') +0.9999 

   AND IRM.NUM_REQUISICAO=RM.NUM_REQUISICAO 

   AND IRM.ANO_REQUISICAO_MATERIAL=RM.ANO_REQUISICAO_MATERIAL 

   AND RM.ANO_REQUISICAO_MATERIAL=CR.ANO_REQUISICAO_MATERIAL 

   AND RM.NUM_REQUISICAO=CR.NUM_REQUISICAO 

   AND CR.IDF_TIPO_DOCUMENTO=17 

   AND CR.NUM_DOCUMENTO=TOS.NUM_TRIAGEM_OS 

   AND TOS.NUM_ORDEM=OS.NUM_ORDEM 

   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO 

   AND CC.COD_GRUPO = GC.COD_GRUPO(+) 

   AND TOS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE 

   AND TOS.SEQ_GRUPO_ESTATISTICA = '24/08/2021 00:00:00'2 

 GROUP BY OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO, OS.ANO_ORDEM_SERVICO, 
OS.COD_CENCUSTO, 

          TOS.COD_UNIDADE_EXECUTANTE, IRM.DTA_MOV_CONTABIL, 
UE.NOM_UNIDADE_EXECUTANTE,   

          GC.COD_GRUPO, GC.DSC_GRUPO, GC.ORD_IMPRESSAO 

 ) X 

 GROUP BY X.COD_GRUPO, X.ORD_IMPRESSAO, X.DSC_GRUPO, X.NOM_UNIDADE_EXECUTANTE, 
X.COD_UNIDADE_EXECUTANTE 

 ORDER BY X.ORD_IMPRESSAO
