prompt Importing table GENERICO.CENTRO_CUSTO_INTEGRACAO...
set feedback off
set define off

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000032', 813);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000033', 814);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000034', 815);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000035', 816);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000036', 817);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000037', 818);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000038', 819);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000039', 820);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000040', 821);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000041', 822);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000042', 823);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000043', 824);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0068', 825);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0069', 826);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00086', 827);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00080', 828);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00081', 829);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00206', 830);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00207', 831);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00210', 832);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00279', 833);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00098', 834);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00217', 835);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00139', 836);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC08030', 837);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00220', 838);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA1200', 839);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA1201', 840);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0114 ', 841);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0115 ', 842);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0116 ', 843);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0100 ', 844);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0102 ', 845);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0113 ', 846);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000010', 847);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000011', 848);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000030', 849);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000044', 850);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000045', 851);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000046', 852);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000047', 853);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000048', 854);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000049', 855);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000050', 856);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000051', 857);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000052', 858);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000053', 859);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000054', 860);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000055', 861);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000056', 862);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000057', 863);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000058', 864);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000059', 865);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000060', 866);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000061', 867);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000062', 868);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000063', 869);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0300', 870);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0301', 871);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0400', 872);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0401', 873);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0500', 874);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0501', 875);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAB00034', 876);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00180', 877);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00083', 878);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00084', 879);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00085', 880);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00199', 881);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00200', 882);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00086', 883);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0076', 884);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00092', 885);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00212', 886);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00213', 887);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCAA00058', 888);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAB00046', 889);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA1100', 890);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA2000', 891);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA2100', 892);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA3000', 893);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA3100', 894);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA4000', 895);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA4100', 896);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA4110', 897);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA4111', 898);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA4120', 899);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA4121', 900);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0100', 901);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0101', 902);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0200', 903);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0201', 904);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0600', 905);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0601', 906);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0700', 907);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0701', 908);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0800', 909);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0801', 910);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0900', 911);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0901', 912);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA1300', 913);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA1301', 914);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00123', 915);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00135', 916);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC03032', 46);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC06057', 47);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC0002X', 48);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABA01013', 49);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABF00017', 50);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABI00037', 51);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABS0001X', 52);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAB0102X', 53);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDC00033', 54);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00085', 55);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04032', 56);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CHAA00016', 57);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00001', 58);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFDC06036', 59);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECB03021', 60);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACD02034', 61);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC04012', 62);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABE00011', 63);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACE01012', 64);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CHAB00023', 65);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC07037', 66);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00002', 67);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00048', 68);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00049', 69);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CADA00026', 70);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACJ01011', 71);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00041', 72);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00121', 73);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00003', 74);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00004', 75);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00005', 76);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00146', 77);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACR00011', 78);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABL00011', 79);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00109', 80);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFB00020', 81);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFD04014', 82);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFAC05017', 83);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00051', 84);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00052', 85);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00056', 86);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFDA0001X', 87);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00032', 88);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEA00016', 89);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEC00017', 90);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAF00028', 91);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC01018', 92);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC02047', 93);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04093', 94);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACQ03017', 95);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAA01015', 96);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA00020', 97);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABT00017', 98);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACL00019', 99);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA0009X', 100);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO00040', 101);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00013', 102);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACF03039', 103);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00158', 104);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC02010', 105);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00080', 106);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC0016X', 107);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACE04049', 108);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00123', 109);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00007', 110);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00008', 111);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFAB00037', 112);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC02022', 113);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGCA00011', 114);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00057', 115);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00058', 116);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACR00035', 117);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00019', 118);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA02016', 119);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDC0001X', 120);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDC00021', 121);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEA0101X', 122);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEA02013', 123);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFAB05011', 124);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAB03015', 125);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0040', 126);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0041', 127);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAG00011', 128);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECB00019', 129);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECB01024', 130);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC02011', 131);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC02023', 132);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC02035', 133);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC0050X', 134);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00055', 135);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABN00048', 136);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAC00048', 137);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGED03013', 138);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGED04017', 139);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGED06014', 140);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEE00018', 141);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFA00013', 142);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFC00014', 143);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFC0102X', 144);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFD0001X', 145);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00027', 146);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEC02014', 147);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00012', 148);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00038', 149);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFDB00015', 150);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFDB06017', 151);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFDC05019', 152);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGAB00012', 153);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGCB00017', 154);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGCC0201X', 155);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECB03033', 156);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECB00044', 157);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM01043', 158);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFAB00013', 159);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA0301X', 160);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00024', 161);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00025', 162);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0042', 163);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00183', 164);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00073', 165);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGAA00042', 166);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEE01011', 167);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABD0003X', 168);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACE0203X', 169);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACE0301X', 170);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACE04013', 171);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACF03015', 172);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00040', 173);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00050', 174);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACG01013', 175);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACG05018', 176);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACG05031', 177);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACH01019', 178);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM02059', 179);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACI01014', 180);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00075', 181);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00055', 182);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00523', 183);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACJ04012', 184);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACH04021', 185);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00031', 186);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00032', 187);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00061', 188);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00040', 189);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00097', 190);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEA00028', 191);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00010', 192);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00011', 193);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABT00030', 194);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA0005X', 195);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFA01017', 196);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFD00021', 197);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCB00018', 198);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA03021', 199);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFAC00019', 200);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAH00017', 201);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00316', 202);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO00027', 203);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC06033', 204);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC0601X', 205);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00049', 206);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACE02041', 207);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACG04014', 208);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACJ03019', 209);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA01024', 210);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACR00023', 211);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA0005X', 212);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00010', 213);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00027', 214);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC03015', 215);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04044', 216);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04056', 217);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04068', 218);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0038', 219);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC0407X', 220);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC05012', 221);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEDB03017', 222);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEDC00011', 223);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAB01031', 224);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACP01038', 225);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACQ00016', 226);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CADA00014', 227);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAA00011', 228);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAC00012', 229);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAC0103X', 230);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00028', 231);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO03053', 232);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAD00018', 233);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBBA02016', 234);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00088', 235);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00024', 236);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCAA00010', 237);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCEA0001X', 238);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA00032', 239);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACP01014', 240);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABS00069', 241);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABU00012', 242);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACA00017', 243);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC07049', 244);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC07050', 245);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACD02010', 246);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO00064', 247);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACG03010', 248);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM03015', 249);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN0001X', 250);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN01037', 251);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN03010', 252);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN04014', 253);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO01019', 254);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO02012', 255);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO03016', 256);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK02010', 257);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM01018', 258);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACJ00018', 259);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEDB00016', 260);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC01011', 261);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC03019', 262);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00026', 263);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC04036', 264);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC05016', 265);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00122', 266);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00118', 267);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00120', 268);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC07013', 269);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('BAAA0001X', 270);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABA02017', 271);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAB02011', 272);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA02016', 273);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAB01018', 274);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00012', 275);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00024', 276);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00048', 277);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00061', 278);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABB00015', 279);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABC00010', 280);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABD00016', 281);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABF00029', 282);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABG00012', 283);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00115', 284);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00106', 285);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00118', 286);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABH00018', 287);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00180', 288);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABI00025', 289);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABJ00010', 290);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABK00016', 291);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABN00012', 292);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABN00036', 293);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABS00021', 294);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABS00057', 295);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACF0102X', 296);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC05028', 297);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00213', 298);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA0012X', 299);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00012', 300);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00074', 301);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00298', 302);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00056', 303);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00062', 304);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00074', 305);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCEB00027', 306);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACL00020', 307);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00139', 308);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN00033', 309);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAB02023', 310);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA02028', 311);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFDA00021', 312);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCEB00039', 313);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00086', 314);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00140', 315);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00013', 316);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00014', 317);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00015', 318);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00016', 319);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00017', 320);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00018', 321);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00019', 322);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00020', 323);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00021', 324);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00022', 325);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00023', 326);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00024', 327);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00025', 328);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00029', 329);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00155', 330);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00036', 331);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0011', 332);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0012', 333);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0013', 334);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0014', 335);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0015', 336);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0016', 337);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0018', 338);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0019', 339);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0020', 340);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0022', 341);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0023', 342);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0024', 343);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0025', 344);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0026', 345);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0027', 346);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0028', 347);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0029', 348);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0030', 349);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0031', 350);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0032', 351);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0033', 352);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0034', 353);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0035', 354);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0036', 355);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0037', 356);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00030', 357);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEDB03030', 358);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00206', 359);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0010', 360);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0008', 361);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0001', 362);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0002', 363);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0003', 364);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0004', 365);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0007', 366);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0009', 367);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA00068', 368);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA0007X', 369);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA00081', 370);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA00093', 371);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA0010X', 372);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00033', 373);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00034', 374);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00035', 375);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00152', 376);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00164', 377);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00176', 378);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00188', 379);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA0019X', 380);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAB00022', 381);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00218', 382);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00037', 383);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFB00019', 384);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00015', 385);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFAD00014', 386);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAE00010', 387);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC0410X', 388);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAB02059', 389);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0039', 390);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEDB00041', 391);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBBE00010', 392);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA00019', 393);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABT00029', 394);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN01013', 395);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO0401X', 396);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACI03011', 397);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00043', 398);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM03039', 399);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABA00045', 400);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAD00027', 401);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04081', 402);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBCA00016', 403);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM02035', 404);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00062', 405);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACF01018', 406);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('AAAA00017', 407);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00077', 408);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAD0002X', 409);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAC0001X', 410);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBBD00015', 411);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00018', 412);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK03014', 413);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00036', 414);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00011', 415);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00143', 416);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CDAA0001X', 417);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM02011', 418);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00249', 419);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00103', 420);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEE01023', 421);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACM01031', 422);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABH00055', 423);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00511', 424);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN01050', 425);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABA02029', 426);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEC00029', 427);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00073', 428);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGEE01035', 429);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00044', 430);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAD00031', 431);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00052', 432);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAB00010', 433);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCEB00015', 434);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00262', 435);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00274', 436);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC00286', 437);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABS00070', 438);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00064', 439);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAA00059', 440);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACG04063', 441);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFA00128', 442);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACF04019', 443);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00076', 444);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABH00511', 445);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('AAAA00029', 446);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04214', 447);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00039', 448);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAA00179', 449);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00127', 450);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00104', 451);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00105', 452);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00106', 453);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00107', 454);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00097', 455);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00009', 456);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00126', 457);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00012', 458);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00013', 459);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00014', 460);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00016', 461);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00017', 462);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00018', 463);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00019', 464);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00022', 465);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00023', 466);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACO04100', 467);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABU00024', 468);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0044', 469);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0045', 470);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0046', 471);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0047', 472);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0048', 473);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0057', 474);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0058', 475);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0059', 476);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0060', 477);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0061', 478);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0062', 479);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0063', 480);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0064', 481);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0066', 482);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0067', 483);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00043', 484);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00044', 485);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00045', 486);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00047', 487);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00048', 488);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00127', 489);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00049', 490);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00059', 491);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00060', 492);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00061', 493);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00062', 494);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00063', 495);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00064', 496);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00065', 497);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00066', 498);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00067', 499);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00068', 500);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00069', 501);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00070', 502);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00071', 503);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00072', 504);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00074', 505);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00046', 506);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00076', 507);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00129', 508);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00130', 509);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00078', 510);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00132', 511);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00133', 512);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00079', 513);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00134', 514);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00135', 515);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00136', 516);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00137', 517);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00138', 518);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00139', 519);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00140', 520);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00141', 521);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00142', 522);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00143', 523);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00144', 524);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00145', 525);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00026', 526);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00027', 527);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00028', 528);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00029', 529);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00031', 530);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00032', 531);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00033', 532);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00035', 533);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00041', 534);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00042', 535);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00044', 536);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00045', 537);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00046', 538);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00047', 539);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00048', 540);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00049', 541);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00050', 542);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00051', 543);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00053', 544);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00054', 545);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00055', 546);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00056', 547);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00058', 548);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00060', 549);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00061', 550);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00062', 551);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00063', 552);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00065', 553);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00067', 554);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00068', 555);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00070', 556);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00071', 557);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00072', 558);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00073', 559);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00075', 560);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00076', 561);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00077', 562);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00078', 563);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00079', 564);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00080', 565);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00082', 566);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00084', 567);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00085', 568);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00086', 569);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00088', 570);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00090', 571);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00091', 572);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00092', 573);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00093', 574);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00094', 575);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00099', 576);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00100', 577);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00112', 578);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00116', 579);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00117', 580);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00125', 581);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00124', 582);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0049', 583);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0050', 584);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0051', 585);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0052', 586);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0054', 587);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0055', 588);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0056', 589);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00146', 590);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00147', 591);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00148', 592);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00149', 593);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00150', 594);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00151', 595);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00152', 596);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00153', 597);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00154', 598);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00155', 599);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00156', 600);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00157', 601);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00158', 602);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00159', 603);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00160', 604);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00161', 605);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00162', 606);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00164', 607);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00165', 608);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00166', 609);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00167', 610);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00168', 611);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00170', 612);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00171', 613);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0070', 614);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00176', 615);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00177', 616);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00178', 617);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00243', 618);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00089', 619);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00091', 620);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00267', 621);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0077', 622);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00093', 623);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECC04226', 624);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00280', 625);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00219', 626);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCB0002X', 627);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA5000', 628);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CABU00036', 629);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('AAAA00030', 630);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0080', 631);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0112 ', 632);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0081', 633);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0082', 634);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000002', 635);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000003', 636);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000004', 637);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000005', 638);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000006', 639);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000007', 640);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000008', 641);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000009', 642);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC08029', 643);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00174', 644);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CHAA00028', 645);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00181', 646);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00182', 647);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00183', 648);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00184', 649);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00185', 650);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00186', 651);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00187', 652);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00188', 653);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00189', 654);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00190', 655);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00191', 656);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00192', 657);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00193', 658);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00194', 659);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00195', 660);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00196', 661);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00231', 662);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCAA00046', 663);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('DAAB00058', 664);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00094', 665);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00068', 666);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACN00057', 667);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00218', 668);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA5100', 669);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA6100', 670);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA7100', 671);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA8100', 672);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA9100', 673);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0101 ', 674);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0110 ', 675);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0111 ', 676);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0109 ', 677);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0106 ', 678);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0107 ', 679);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00103', 680);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000012', 681);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00223', 682);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00225', 683);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00116', 684);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGFA01029', 685);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA0203X', 686);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00310', 687);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000064', 688);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000065', 689);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000066', 690);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000067', 691);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000068', 692);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000069', 693);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00169', 694);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00175', 695);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00179', 696);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00197', 697);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00198', 698);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00082', 699);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0072', 700);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00201', 701);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACQ00028', 702);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0075', 703);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00202', 704);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00203', 705);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00204', 706);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00087', 707);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CBAA00060', 708);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACQ0003X', 709);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00090', 710);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00102', 711);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA5200', 712);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA5210', 713);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0108 ', 714);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAAD0103 ', 715);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCA00140', 716);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000070', 717);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000071', 718);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000072', 719);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000073', 720);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00020', 721);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00131', 722);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00034', 723);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00059', 724);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00087', 725);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0053', 726);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00095', 727);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00105', 728);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000074', 729);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00322', 730);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00106', 731);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00334', 732);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00346', 733);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00358', 734);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00107', 735);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0083', 736);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00371', 737);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00226', 738);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000077', 739);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0084', 740);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00163', 741);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CECB03045', 742);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEDB03042', 743);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CEAA00111', 744);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00208', 745);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00209', 746);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00098', 747);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HERP00088', 748);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00255', 749);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00211', 750);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACC01035', 751);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0078', 752);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACD02022', 753);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACD02046', 754);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCAA0006X', 755);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCAA00071', 756);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00214', 757);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00215', 758);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00216', 759);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCAA00083', 760);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00292', 761);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA6000', 762);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA7000', 763);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA8000', 764);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA9000', 765);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00104', 766);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00222', 767);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000075', 768);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0010', 769);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA0011', 770);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CFCC00116', 771);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA0036X', 772);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA00383', 773);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000076', 774);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000084', 775);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00008', 776);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00172', 777);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00173', 778);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CCAA00022', 779);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0071', 780);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0073', 781);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0074', 782);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00205', 783);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CAAA0022X', 784);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('MATER0079', 785);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA0007X', 786);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00081', 787);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00093', 788);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA0010X', 789);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CGDA00111', 790);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA1000', 791);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA5110', 792);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('FAEPA5111', 793);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HEAB00221', 794);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('CACK00104', 795);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000001', 796);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000013', 797);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000014', 798);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000015', 799);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000016', 800);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000017', 801);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000018', 802);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000019', 803);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000020', 804);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000021', 805);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000023', 806);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000024', 807);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000025', 808);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000026', 809);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000028', 810);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000029', 811);

insert into GENERICO.CENTRO_CUSTO_INTEGRACAO (COD_CENCUSTO, DSC_GLPI_GROUP_ID)
values ('HES000031', 812);

prompt Done.
