insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 1);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 2);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 3);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 4);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 5);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 6);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 7);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 8);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 9);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 10);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 11);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 12);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 13);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 14);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 15);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 16);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 17);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 18);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 19);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 20);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 21);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 22);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 23);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 24);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 25);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 26);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 27);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 28);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 29);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 30);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 31);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 32);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 33);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 34);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 35);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 37);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 38);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 39);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 40);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 41);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 42);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 43);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 44);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 45);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 46);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 47);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 48);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 49);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 50);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 51);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 56);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 57);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 58);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 59);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 60);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 266);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (58127, 418);


