--Demanda os
SELECT * 
 FROM material m
 WHERE m.cod_grupo = 90
 AND m.idf_ativo = 'S';
 
 SELECT *
  FROM grupo g
  WHERE g.cod_alinea = 21;
  
  select * from ESTOQUE.ALINEA t;
  --PS: 21
  -----------------------------------------------
  SELECT *
   FROM AGENDA_AUT_ENTREGA_SERVICO ag
   WHERE 1 = 1
   AND ag.dta_agendamento >= to_date('01/01/2022', 'DD/MM/YYYY')   
   AND ag.idf_recebido = 'S';
  ------------------------------------------------
  SELECT A.NUM_DOC_FINANCEIRO, A.COD_INSTITUICAO, A.COD_TIPO_DOCUMENTO, A.DTA_EMISSAO, A.ANO_MES_COMPETENCIA, 
       A.NUM_DOCUMENTO, A.VLR_DOCUMENTO, A.DTA_HOR_LANCAMENTO, A.NUM_USER_LANCAMENTO, A.IDF_OPERACAO,
       A.IDF_ORIGEM, A.IDF_PROVISAO, A.STA_DOCUMENTO, A.DSC_SERIE, A.COD_CLIENTE, A.COD_FORNECEDOR, 
       A.COD_FAVORECIDO, A.OBS_DOCUMENTO, A.DTA_HOR_EXP_CONTABIL, A.COD_RECEITA_TRIBUTO, A.DTA_ENTRADA_ESTOQUE, 
       A.DSC_SERIE || ' - ' || B.NOM_FORNECEDOR NOM_FORNECEDOR,
       NVL(A.STA_DOCUMENTO, '0') STATUS_DOCUMENTO,
       B.CGC_FORNECEDOR,
       C.NOM_FANTASIA,
       D.NUM_AUT_ENTREGA_SERVICO, D.DTA_AGENDAMENTO, D.VLR_PREVISTO, D.VLR_FATURADO, D.VLR_FATURADO_MOBRA,
       D.VLR_FATURADO_MATERIAL, D.IDF_STATUS_AGENDA, D.DSC_OBS_CANCELA_AGENDA, 
       E.NUM_COTACAO_SERVICO, E.NUM_AUTORIZACAO_ENTREGA, E.ANO_AUTORIZACAO_ENTREGA,
       E.NUM_AUTORIZACAO_ENTREGA||'/'||E.ANO_AUTORIZACAO_ENTREGA NUM_AF,
       F.DTA_EMISSAO, F.OBS_AUTORIZACAO
 FROM DOCUMENTO_FINANCEIRO A
      ,FORNECEDOR        B
      ,INSTITUICAO       C
      ,AGENDA_AUT_ENTREGA_SERVICO D
      ,AUTORIZACAO_ENTREGA_SERVICO E
      ,AUTORIZACAO_ENTREGA F
 WHERE 1 = 1
--   AND ((A.NUM_DOC_FINANCEIRO = :NUM_DOC_FINANCEIRO))
   AND (A.COD_FORNECEDOR = B.COD_FORNECEDOR)
   AND (A.COD_INSTITUICAO = C.COD_INSTITUICAO)
   AND (A.NUM_DOC_FINANCEIRO = D.NUM_DOC_FINANCEIRO)
   AND (D.NUM_AUT_ENTREGA_SERVICO = E.NUM_AUT_ENTREGA_SERVICO)
   AND (E.NUM_AUTORIZACAO_ENTREGA = F.NUM_AUTORIZACAO_ENTREGA)
   AND (E.ANO_AUTORIZACAO_ENTREGA = F.ANO_AUTORIZACAO_ENTREGA)
   AND (E.COD_INSTITUICAO = F.COD_INSTITUICAO)
 ORDER BY A.DTA_EMISSAO DESC;
 ------------------------------------------------------------------
  SELECT A.NUM_REQUISICAO, A.ANO_REQUISICAO_MATERIAL, A.COD_CENCUSTO_EXECUTANTE, 
        A.NUM_REQUISICAO||'/'||A.ANO_REQUISICAO_MATERIAL REQUISICAO, 
        A.NUM_REQUISICAO, A.ANO_REQUISICAO_MATERIAL, 
        TO_CHAR(B.DTA_REQUISICAO,'DD/MM/YYYY HH24:MI:SS') DTA_REQUISICAO,
        B.COD_CENCUSTO_ATENDENTE, 
        DECODE(B.IDF_STATUS_REQUISICAO,0,'ABERTA',1,'IMPRESSA',2,'ATENDIDA',3,'CANCELADA') STATUS_REQUISICAO, 
        TO_CHAR(C.DTA_HOR_TRIAGEM,'DD/MM/YYYY HH24:MI:SS') DTA_TRIAGEM, C.NUM_ORDEM, 
        D.COD_SITUACAO_OS,  D.NUM_ORDEM_SERVICO||'/'||D.ANO_ORDEM_SERVICO NUM_OS, 
        D.NUM_ORDEM_SERVICO, D.ANO_ORDEM_SERVICO, 
        E.NOM_USUARIO||' '||E.SBN_USUARIO USAURIO, UE.NOM_UNIDADE_EXECUTANTE 
 FROM COMPLEMENTO_REQUISICAO A,  REQUISICAO_MATERIAL B, TRIAGEM_ORDEM_SERVICO C, 
      ORDEM_SERVICO D, USUARIO E ,
      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE 
       FROM UNIDADE_EXECUTANTE 
       START WITH COD_UNIDADE_EXECUTANTE = 2
       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE 
       
 WHERE 1 = 1
 -- AND B.COD_CENCUSTO_ATENDENTE = :COD_CENCUSTO_ATENDENTE 
  AND  C.COD_UNIDADE_EXECUTANTE = UE.COD_UNIDADE_EXECUTANTE 
  AND  C.NUM_TRIAGEM_OS = A.NUM_DOCUMENTO 
  AND  A.NUM_REQUISICAO = B.NUM_REQUISICAO 
  AND  A.ANO_REQUISICAO_MATERIAL = B.ANO_REQUISICAO_MATERIAL 
  AND  A.IDF_TIPO_DOCUMENTO = 17 
  AND  C.NUM_ORDEM = D.NUM_ORDEM 
  AND  B.IDF_SOLICITANTE = E.NUM_USER_BANCO 
  AND D.dta_criacao_os > (SYSDATE - 180 );
  ------------------------------------------------------------
  SELECT AAES.NUM_AUT_ENTREGA_SERVICO, AAES.IDF_RECEBIDO,
       AE.NUM_AUTORIZACAO_ENTREGA, AE.ANO_AUTORIZACAO_ENTREGA, AE.COD_INSTITUICAO,
       V.NOM_FANTASIA, AE.COD_FORNECEDOR, F.NOM_FORNECEDOR, AAES.DTA_AGENDAMENTO,
       TO_CHAR(AAES.DTA_AGENDAMENTO,'DD/MM/YYYY HH24:MI:SS') "DTA_AGENDA",
--       AES.VLR_CONTRATACAO VLR_PREVISTO, AES.VLR_CONTRATACAO_MATERIAL,
--       AES.VLR_CONTRATACAO_MOBRA,
       AAES.VLR_PREVISTO, AAES.VLR_FATURADO_MATERIAL VLR_CONTRATACAO_MATERIAL,
       AAES.VLR_FATURADO_MOBRA VLR_CONTRATACAO_MOBRA,
       AE.NUM_AUTORIZACAO_ENTREGA||'-'||AE.ANO_AUTORIZACAO_ENTREGA "NUM_AF",
       AES.DSC_SERVICO_CONTRATADO, AES.NUM_AUT_ENTREGA_SERVICO
       , OAES.COD_SERVICO_NFSE
FROM AUTORIZACAO_ENTREGA_SERVICO AES, COTACAO_PEDIDO_SERVICO CS,
     PEDIDO_SERVICO PS, TRIAGEM_ORDEM_SERVICO TS, ORDEM_SERVICO OS,
     AUTORIZACAO_ENTREGA AE, V_INSTITUICAO_ORDEM_SERVICO V, FORNECEDOR F,
     AGENDA_AUT_ENTREGA_SERVICO AAES
     , GENERICO.ONERACAO_AUT_ENTREGA_SERVICO OAES
WHERE (AES.NUM_AUTORIZACAO_ENTREGA = AE.NUM_AUTORIZACAO_ENTREGA  AND
       AES.ANO_AUTORIZACAO_ENTREGA = AE.ANO_AUTORIZACAO_ENTREGA  AND
       AES.COD_INSTITUICAO = AE.COD_INSTITUICAO )
  AND AES.NUM_COTACAO_SERVICO = CS.NUM_COTACAO_SERVICO
  AND AES.NUM_AUT_ENTREGA_SERVICO = AAES.NUM_AUT_ENTREGA_SERVICO
  AND AAES.IDF_RECEBIDO = 'N'
  AND CS.NUM_PEDIDO_SERVICO = PS.NUM_PEDIDO_SERVICO
  AND PS.IDF_ESTAGIO_PEDIDO <> 8
  AND PS.NUM_TRIAGEM_OS = TS.NUM_TRIAGEM_OS
  AND TS.NUM_ORDEM = OS.NUM_ORDEM
  AND OS.COD_SITUACAO_OS NOT IN (4,5,6,8,9,13)
  --AND AE.COD_FORNECEDOR = :COD_FORNECEDOR
  AND AE.COD_FORNECEDOR = F.COD_FORNECEDOR
  AND AE.COD_INSTITUICAO = V.COD_INSTITUICAO
  AND AES.NUM_AUT_ENTREGA_SERVICO = OAES.NUM_AUT_ENTREGA_SERVICO
  AND V.COD_INSTITUICAO = 1
  AND os.dta_criacao_os > (SYSDATE - 180 )
ORDER BY  AES.NUM_AUT_ENTREGA_SERVICO;--, AE.NUM_AUTORIZACAO_ENTREGA, AE.ANO_AUTORIZACAO_ENTREGA
  -----------------------------------------------------------
 
 
 SELECT *
  FROM ordem_servico os
  WHERE os.cod_unidade_executante = 2
  AND os.dta_criacao_os > (SYSDATE - 180 );
-------------------------------------------------------------

SELECT *
  FROM DOCUMENTO_FINANCEIRO d
  WHERE d.dta_emissao  > (SYSDATE - 180 );
