SELECT TO_CHAR(DTA_HOR_FIM, 'DD/MM/YYYY  -  DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE') DIA,       
       COUNT(A.NUM_SOL_TRANSPORTE) QTD
  FROM TRANSPORTE_MATERIAL A

 WHERE 1 = 1
   AND TRUNC(DTA_HOR_FIM) BETWEEN to_date('27/01/2020', 'DD/MM/YYYY') AND to_date('27/12/2021', 'DD/MM/YYYY')      
   AND IDF_ATENDIMENTO = 0

 GROUP BY TO_CHAR(DTA_HOR_FIM, 'DD/MM/YYYY  -  DAY',  'NLS_DATE_LANGUAGE=PORTUGUESE');
 ------------------------------------------------------------------------------------
 SELECT COUNT(A.NUM_SOL_TRANSPORTE) TOTAL_LOCAL, B.SGL_LOCAL, B.NOM_LOCAL 

FROM TRANSPORTE_MATERIAL A, LOCAL B

WHERE B.COD_LOCAL = A.COD_LOCAL_SOLICITANTE
      AND TRUNC(DTA_HOR_FIM) BETWEEN to_date('27/01/2020', 'DD/MM/YYYY') AND to_date('27/12/2021', 'DD/MM/YYYY')
      AND IDF_ATENDIMENTO =0

GROUP BY B.SGL_LOCAL, B.NOM_LOCAL

ORDER BY B.NOM_LOCAL;
