SELECT A.COD_ESTRUTURA, A.COD_INSTITUICAO,
       SUBSTR(PCG_COMPRAS.FC_ESTRUTURA_ORCAMENTARIA(A.COD_INSTITUICAO, A.COD_ESTRUTURA),1,100)||' ('||NVL(B.NOM_FANTASIA,B.NOM_INSTITUICAO)||')' ESTRUTURA
FROM USUARIO_ESTRUTURA_ORCAMENTARIA X, ESTRUTURA_ORCAMENTARIA A, INSTITUICAO B
WHERE X.NUM_USER_BANCO=PCG_FUNCAO_GENERICA.FC_NUM_USER_BANCO
  AND X.COD_INSTITUICAO=A.COD_INSTITUICAO
  AND X.COD_ESTRUTURA=A.COD_ESTRUTURA
  AND A.IDF_ATIVA='S'
  AND A.COD_INSTITUICAO=B.COD_INSTITUICAO
  and ESTOQUE.FCN_INST_ONERACAO(X.COD_INSTITUICAO, X.COD_ESTRUTURA) = 2
  AND 0=(SELECT COUNT(*) FROM ESTRUTURA_ORCAMENTARIA
         WHERE COD_INSTITUICAO_PAI=A.COD_INSTITUICAO
           AND COD_ESTRUTURA_PAI=A.COD_ESTRUTURA)
ORDER BY ESTRUTURA;
