SELECT COUNT(1) OVER() TOTAL_FICHAS, 
       F.SEQ_FICHA_ANESTESICA,
       decode(F.IDF_STATUS,0,'PENDENTE',1,'PROVISÓRIA',2,'DEFINITIVA',3,'CANCELADA') SITUACAO,
       PR.NOM_PROFISSIONAL || ' ' || PR.SBN_PROFISSIONAL PROFISSIONAL,-- PR.CPF_PROFISSIONAL,
       A.DTA_CIR_PROPOSTA,
       F.DTA_HOR_CADASTRO,
       F.DTA_HOR_FINALIZACAO,
       'RE' || LPAD(RLC.SEQ_REPOSITORIO, 8, '0') SEQ_REPOSITORIO,
       NVL(RLC.DSC_IDENTIFICACAO, 'NÃO VINCULOU O KIT') DSC_IDENTIFICACAO,
       LR.NUM_LACRE LACRE_RETORNO,
       ML.NOM_LOCAL SALA_CIRURGICA,
       E.SGL_ESPECIALIDADE_HC,
       P.COD_PACIENTE,
       P.NOM_PACIENTE || ' ' || P.SBN_PACIENTE PACIENTE,
       F.SEQ_AGENDA_CIRURGIA,
       DECODE(A.IDF_STATUS_CIRURGIA, 0,'ABERTA',2,'REALIZADA',9,'EM CIRURGIA') STATUS_CIRURGIA,
       SUBSTR(FCN_LINHA_COLUNA('SELECT PR.NOM_PROCEDIMENTO_HC 
                                  FROM PROCEDIMENTO_HC PR, AGENDA_PROCEDIMENTO_HC AG 
                                 WHERE PR.COD_PROCEDIMENTO_HC = AG.COD_PROCEDIMENTO_HC 
                                   AND AG.SEQ_AGENDA_CIRURGIA = ' || A.SEQ_AGENDA_CIRURGIA, ' / '),1,255) PROCEDIMENTO,
       LR.SEQ_LACRE_REPOSITORIO,
       TS.COD_SITUACAO ||'-' || TS.NOM_SITUACAO SITUACAO_LACRE,
       F.DSC_JUSTIF_SEM_PSICOBOX,
       --f.idf_status,
       A.SEQ_ATENDIMENTO
  FROM FICHA_ANESTESICA           F,
       AGENDA_CIRURGIA            A, 
       PROFISSIONAL               PR,
       LACRE_REPOSITORIO          LR,
       REPOSITORIO_LISTA_CONTROLE RLC,
       PACIENTE                   P,
       TIPO_SITUACAO_HC           TS,
       
       MAPEAMENTO_LOCAL           ML,
       ESPECIALIDADE_HC           E
 WHERE F.SEQ_AGENDA_CIRURGIA= A.SEQ_AGENDA_CIRURGIA
   AND F.COD_PROFISSIONAL = PR.COD_PROFISSIONAL(+)
   AND LR.SEQ_REPOSITORIO = RLC.SEQ_REPOSITORIO(+)
   AND LR.SEQ_AGENDA_CIRURGIA(+) = F.SEQ_AGENDA_CIRURGIA
   AND F.COD_PACIENTE = P.COD_PACIENTE
   AND LR.COD_SITUACAO_ATUAL = TS.COD_SITUACAO(+)
   AND A.NUM_SEQ_LOCAL_CIRURGIA = ML.NUM_SEQ_LOCAL
   AND A.COD_ESPECIALIDADE_HC = E.COD_ESPECIALIDADE_HC(+)
   AND A.NUM_SEQ_CC = 6495 --15313 HES
   AND F.DTA_HOR_CADASTRO BETWEEN TO_DATE('&DTA_INI', 'DD/MM/YYYY') AND
       TO_DATE('&DTA_FIM', 'DD/MM/YYYY') + .99999
   AND PR.NUM_USER_BANCO NOT IN (66857,54425,51855)
--   AND F.DSC_JUSTIF_SEM_PSICOBOX IS NOT NULL       
--   AND ML.NOM_LOCAL LIKE '%&NUM_SALA%'
  -- AND F.IDF_STATUS = 0 AND F.COD_PACIENTE <> '0919953H'
--   AND F.COD_PACIENTE IN ('1445194A','1546913D','1712697A')
--   AND LR.SEQ_REPOSITORIO = 472
--AND F.SEQ_FICHA_ANESTESICA = 49227
--AND PR.NOM_PROFISSIONAL LIKE 'MURIELE BATISTA%'
 ORDER BY /*ML.NOM_LOCAL, */F.DTA_HOR_CADASTRO, F.DTA_HOR_FINALIZACAO;
--KITS UTILIZADOS NO PERIODO
SELECT 'RE' || LPAD(RLC.SEQ_REPOSITORIO, 8, '0') SEQ_REPOSITORIO,
       RLC.DSC_IDENTIFICACAO,
       TS.COD_SITUACAO,
       TS.NOM_SITUACAO,
       LR.DTA_CADASTRO,
       LTO.DSC_TIPO_OCORRENCIA,
       U.NOM_USUARIO || ' ' || U.SBN_USUARIO USUARIO,
       lr.seq_lacre_repositorio
  FROM LACRE_REPOSITORIO          LR,
       REPOSITORIO_LISTA_CONTROLE RLC,
       TIPO_SITUACAO_HC           TS,
       LISTA_CONTROLE             LC,
       LACRE_TIPO_OCORRENCIA      LTO,
       USUARIO                    U
 WHERE LR.SEQ_REPOSITORIO = RLC.SEQ_REPOSITORIO
   AND LR.COD_SITUACAO_ATUAL = TS.COD_SITUACAO
   AND RLC.SEQ_LISTA_CONTROLE = LC.SEQ_LISTA_CONTROLE
   AND LR.SEQ_LACRE_TIP_OCORRENCIA = LTO.SEQ_LACRE_TIP_OCORRENCIA
   AND LR.NUM_USER_CADASTRO = U.NUM_USER_BANCO(+)
   AND LR.DTA_CADASTRO BETWEEN TO_DATE('&DTA_INI', 'DD/MM/YYYY') AND
       TO_DATE('&DTA_FIM', 'DD/MM/YYYY') + .99999
   AND LC.COD_INSTITUTO = 7
  -- AND LR.SEQ_REPOSITORIO = 472
 ORDER BY LR.DTA_CADASTRO;
SELECT F.IDF_STATUS, F.DSC_JUSTIF_SEM_PSICOBOX, F.*, ROWID FROM FICHA_ANESTESICA F WHERE F.SEQ_FICHA_ANESTESICA IN (48652); --45911
SELECT F.*, ROWID FROM COMPLEMENTO_FICHA_ANESTESICA F WHERE F.SEQ_FICHA_ANESTESICA in (37292); 
SELECT F.*, ROWID FROM GENERICO.FICHA_ANEST_CONDICOES_FINAIS F WHERE F.SEQ_FICHA_ANESTESICA in (35541,35542); 
SELECT F.*, ROWID FROM GENERICO.FICHA_ANEST_EVENTOS_ADVERSOS F WHERE F.SEQ_FICHA_ANESTESICA in (35541,35542); 
SELECT F.*, ROWID FROM GENERICO.FICHA_ANEST_POSICIO_DISPO F WHERE F.SEQ_FICHA_ANESTESICA in (36842); 
SELECT Muc., ROWID FROM MATERIAL_USO_CIRURGIA Muc WHERE Muc.SEQ_AGENDA_CIRURGIA IN (&seq_agenda_cirurgia)/ and muc.cod_material = '7610204X'*/;
SELECT M.COD_MATERIAL, M.NOM_MATERIAL, MUS.* FROM MATERIAL_USO_CIRURGIA MUS, MATERIAL M WHERE MUS.COD_MATERIAL = M.COD_MATERIAL AND  MUS.SEQ_AGENDA_CIRURGIA IN (&seq_agenda_cirurgia);
SELECT a.*, rowid FROM ADMIN_MATERIAL_USO_CIRURGIA A WHERE A.SEQ_FICHA_ANESTESICA IN (44172) AND A.SEQ_MATERIAL_USO_CIRURGIA IN (10347827);
SELECT T.*, T.ROWID FROM ESTOQUE.LOTE T WHERE T.NUM_LOTE = &M_NUM_LOTE;
