 
 
 SELECT *
  FROM usuario u
  WHERE upper(u.nom_usuario_banco) = 'ASCOSTA';
  
  'DMSMASCARA' --70709 

 
 /*Funcionario não vê os tipos de patrimônios*/
 SELECT TP.COD_TIPO_PATRIMONIO, TP.DSC_TIPO_PATRIMONIO
FROM TIPO_PATRIMONIO TP
  INNER JOIN USUARIO_TIPO_PATRIMONIO UTP ON UTP.COD_TIPO_PATRIMONIO = TP.COD_TIPO_PATRIMONIO
                                        AND UTP.NUM_USER_BANCO = 70709
  INNER JOIN INSTITUICAO_TIPO_PATRIMONIO ITP ON ITP.COD_TIPO_PATRIMONIO = TP.COD_TIPO_PATRIMONIO
                                            AND ITP.COD_INST_SISTEMA = 1
ORDER BY TP.DSC_TIPO_PATRIMONIO;

SELECT * FROM USUARIO_TIPO_PATRIMONIO  u
WHERE u.num_user_banco = 66827;
