-- Daniel Anselmo

 SELECT 

  (SELECT I.NOM_TIPO_IMAGEM_EQUIPAMENTO

     FROM GENERICO.TIPO_IMAGEM_EQUIPAMENTO I

    WHERE I.SEQ_TIPO_IMAGEM_EQUIPAMENTO = BPTE.SEQ_TIPO_IMAGEM_EQUIPAMENTO) 
TIPO_EQUIPAMENTO,

  COUNT(*) QTD,

  RTRIM(XMLAGG(XMLELEMENT(E, LPAD(BP.NUM_PATRIMONIO,5,'0')||'-'||RPAD(TP.DSC_TIPO_PATRIMONIO,9,' ')
                             ||',   '||DECODE(TO_CHAR(EE.DTA_HOR_DEVOLUCAO,'DD/MM/YYYY'), '01/01/1800', 'EMPRESTADO', 'DISPONIVEL')                             
                             ||',   OS: '||LPAD(OS.NUM_ORDEM_SERVICO,5,'0')||'/'||OS.ANO_ORDEM_SERVICO||' '||RPAD(DECODE(TOS.COD_SITUACAO_OS,   4,'FINALIZADA', 5, 'FINALIZADA', DSC_SITUACAO_OS), 12, ' ' )                       
                             ||',   E: '||EE.DTA_HOR_EMPRESTIMO||', D: '||DECODE(TO_CHAR(EE.DTA_HOR_DEVOLUCAO, 'DD/MM/YYYY'), '01/01/1800', NULL, EE.DTA_HOR_DEVOLUCAO)
                             , ',' || CHR(13)).EXTRACT('//text()') ORDER BY 
                             EE.DTA_HOR_EMPRESTIMO DESC) 
                            .GETCLOBVAL(),  ',') EQUIPAMENTOS

   FROM EMPRESTIMO_EQUIPAMENTO EE

   JOIN GENERICO.BEM_PATRIMONIAL_TP_IMAGEM_EQUI BPTE

     ON BPTE.NUM_BEM = EE.NUM_BEM

   JOIN GENERICO.TIPO_IMAGEM_EQUIPAMENTO TIE

     ON TIE.SEQ_TIPO_IMAGEM_EQUIPAMENTO = BPTE.SEQ_TIPO_IMAGEM_EQUIPAMENTO

   JOIN BEM_PATRIMONIAL BP ON BP.NUM_BEM = EE.NUM_BEM

   JOIN TIPO_PATRIMONIO TP ON TP.COD_TIPO_PATRIMONIO = BP.COD_TIPO_PATRIMONIO

   JOIN CENTRO_CUSTO_BEM_PATRIMONIAL CP ON CP.NUM_BEM = BP.NUM_BEM

      AND CP.COD_CENCUSTO = 'CACK00104' AND CP.DTA_FIM IS NULL

   JOIN ORDEM_SERVICO OS ON OS.NUM_ORDEM = EE.NUM_ORDEM  

   JOIN TIPO_SITUACAO_OS TOS ON TOS.COD_SITUACAO_OS = OS.COD_SITUACAO_OS

  WHERE EE.DTA_HOR_EMPRESTIMO  BETWEEN TO_DATE('01/01/2021', 'DD/MM/YYYY') AND 
TO_DATE('11/01/2021', 'DD/MM/YYYY') 

  GROUP BY BPTE.SEQ_TIPO_IMAGEM_EQUIPAMENTO

  ORDER BY TIPO_EQUIPAMENTO;
  ------------------------------------------------