(SELECT BPTE.NUM_BEM 
    FROM GENERICO.BEM_PATRIMONIAL_TP_IMAGEM_EQUI BPTE
    JOIN GENERICO.TIPO_IMAGEM_EQUIPAMENTO  TIE ON TIE.SEQ_TIPO_IMAGEM_EQUIPAMENTO = BPTE.SEQ_TIPO_IMAGEM_EQUIPAMENTO     
    JOIN GENERICO.ORDEM_SERVICO_TIPO_EMPRESTIMO OSTE  ON OSTE.SEQ_ORDEM_SERV_TIPO_EMPRESTIMO = TIE.SEQ_CODIGO_SISTEMA_ORIGEM) EQUIPAMENTO;
   ---------------------------------------
   SELECT SEQ_ORDEM_SERV_TIPO_EMPRESTIMO,
       NOM_ORDEM_SERV_TIPO_EMPRESTIMO,
       NOM_ABREVIADO_PESQUISA, IDF_ATIVO, 
      IDF_GERAR_RESERVA_PATRIMONIO
FROM GENERICO.ORDEM_SERVICO_TIPO_EMPRESTIMO
WHERE IDF_ATIVO = 0
ORDER BY NOM_ORDEM_SERV_TIPO_EMPRESTIMO;
