SELECT *
 FROM unidade_executante ue
 WHERE ue.cod_unidade_executante IN (6,11,70,5,8,40,28,22,35,25,9,78,30,29,34,39,7,10)
 AND ue.idf_ativo = 1
 ORDER BY ue.cod_unidade_executante;
 
 cod_unidade_executante in (10,25,28,29,30,34,35,39,40,78);
 --10,25,28,29,30,34,35,39,40,78
-----------------------------------
--GRUPO CCUSTO Numero de Minutos trabalhados
 SELECT W.DSC_GRUPO,
        SUM(W.QTD_OS_ABERTA) QTD_OS_ABERTA,
        SUM(W.QTD_OS_CONCLUIDA) QTD_OS_CONCLUIDA,
        SUM(W.QTD_OS_CONCL_EXCLUSIVA) QTD_OS_CONCL_EXCLUSIVA,
        SUM(W.VLR_SERV_EXTO_CONTRATADO) VLR_SERV_EXTO_CONTRATADO,
        SUM(W.VLR_MATERIAL) VLR_MATERIAL,
        SUM(W.VLR_HOR_APONTAMENTO) VLR_HOR_APONTAMENTO,
        SUM(W.VLR_SERV_EXTO_CONTRATADO+W.VLR_MATERIAL+W.VLR_HOR_APONTAMENTO) VLR_TOTAL
 FROM (
 SELECT X.COD_CENCUSTO, X.NOM_CENCUSTO, X.DSC_GRUPO,
        --X.COD_GRUPO, X.NOM_UNIDADE_EXECUTANTE, X.COD_UNIDADE_EXECUTANTE,
        SUM(QTD_OS_ABERTA) QTD_OS_ABERTA,
        SUM(QTD_OS_CONCLUIDA) QTD_OS_CONCLUIDA,
        SUM(QTD_OS_CONCL_EXCLUSIVA) QTD_OS_CONCL_EXCLUSIVA,
        SUM(VLR_SERV_EXTO_CONTRATADO) VLR_SERV_EXTO_CONTRATADO,
        SUM(VLR_MATERIAL) VLR_MATERIAL,
        SUM(VLR_HOR_APONTAMENTO) VLR_HOR_APONTAMENTO--,
 FROM (
 -- OS ABERTA EXCLUSIVAMENTE NO PERIODO
  SELECT A.NUM_ORDEM, A.NUM_ORDEM_SERVICO||'/'||A.ANO_ORDEM_SERVICO NUM_OS, A.COD_CENCUSTO, CC.NOM_CENCUSTO,
        A.COD_UNIDADE_EXECUTANTE, A.DTA_CRIACAO_OS DTA_OCORRENCIA, UE.NOM_UNIDADE_EXECUTANTE, A.COD_SITUACAO_OS,
        0 QTD_OS_CONCLUIDA, 1 QTD_OS_ABERTA, 0 QTD_OS_CANCELADA, 0 QTD_OS_CONCL_EXCLUSIVA, 0 VLR_HOR_APONTAMENTO,
        0 QTD_HOR_APONT,
        0 VLR_SERV_EXTO_CONTRATADO, 0 VLR_SERVICO_EXTERNO_PAGO, 0 VLR_MATERIAL, GC.DSC_GRUPO, GC.COD_GRUPO,
        '' ANO_TRIAGEM, '' DTA_ABERTURA_OS, '' DTA_TRIAGEM, '' DTA_ENCERRAMENTO,
        0 QTD_DIAS_CONCLUSAO, 0 QTD_DIAS_TRIAGEM
 FROM ORDEM_SERVICO A, CENTRO_CUSTO CC, GRUPO_CENCUSTO GC,
      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE
       FROM UNIDADE_EXECUTANTE      
       --START WITH COD_UNIDADE_EXECUTANTE IN (2,5,6,7,8,9,11,22,70,10,25,28,29,30,34,35,39,40,78) --campus
       START WITH COD_UNIDADE_EXECUTANTE IN (23,24,43,50,51,52,79,122) --UE
       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE
 WHERE A.DTA_CRIACAO_OS BETWEEN TO_DATE('01/01/2019 00:00:01','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('31/12/2019 23:59:59','DD/MM/YYYY HH24:MI:SS')
   AND A.COD_UNIDADE_EXECUTANTE = UE.COD_UNIDADE_EXECUTANTE
   AND A.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_GRUPO = GC.COD_GRUPO
 UNION ALL
 -- Valor de Apontamento
 SELECT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO NUM_OS, OS.COD_CENCUSTO, CC.NOM_CENCUSTO,
        TOS.COD_UNIDADE_EXECUTANTE, AA.DTA_HOR_INICIO_ATIVIDADE DTA_OCORRENCIA, UE.NOM_UNIDADE_EXECUTANTE,
        OS.COD_SITUACAO_OS, 0 QTD_OS_CONCLUIDA, 0 QTD_OS_ABERTA, 0 QTD_OS_CANCELADA, 0 QTD_OS_CONCL_EXCLUSIVA,
        AA.VLR_HOR_APONTAMENTO, (AA.DTA_HOR_FIM_ATIVIDADE-AA.DTA_HOR_INICIO_ATIVIDADE)*24 QTD_HOR_APONT,
        0 VLR_SERV_EXTO_CONTRATADO, 0 VLR_SERVICO_EXTERNO_PAGO, 0 VLR_MATERIAL, GCC.DSC_GRUPO, GCC.COD_GRUPO,
        '' ANO_TRIAGEM, '' DTA_ABERTURA_OS, '' DTA_TRIAGEM, '' DTA_ENCERRAMENTO,
        0 QTD_DIAS_CONCLUSAO, 0 QTD_DIAS_TRIAGEM
 FROM APONTAMENTO_ATIVIDADE AA, FUNCIONARIO_ORDEM_SERVICO FOS,
      TRIAGEM_ORDEM_SERVICO TOS, ORDEM_SERVICO OS, CENTRO_CUSTO CC, GRUPO_CENCUSTO GCC,
      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE
       FROM UNIDADE_EXECUTANTE
       --START WITH COD_UNIDADE_EXECUTANTE IN (2,5,6,7,8,9,11,22,70,10,25,28,29,30,34,35,39,40,78) --campus
       START WITH COD_UNIDADE_EXECUTANTE IN (23,24,43,50,51,52,79,122) --UE
       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE
 WHERE AA.DTA_HOR_INICIO_ATIVIDADE BETWEEN TO_DATE('01/01/2019','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('31/12/2019','DD/MM/YYYY HH24:MI:SS') +0.9999
   AND AA.SEQ_FUNC_ORDEM_SERVICO=FOS.SEQ_FUNC_ORDEM_SERVICO
   AND FOS.NUM_TRIAGEM_OS=TOS.NUM_TRIAGEM_OS
   AND TOS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE
   AND TOS.NUM_ORDEM=OS.NUM_ORDEM
   AND OS.COD_SITUACAO_OS IN (4,5,6,13)
   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_GRUPO = GCC.COD_GRUPO
   AND TOS.SEQ_GRUPO_ESTATISTICA = 123--:SEQ_GRUPO_ESTATISTICA
 UNION ALL
 -- Numero de OS finalizadas, na oficina que concluiu a OS
 SELECT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO NUM_OS, OS.COD_CENCUSTO, CC.NOM_CENCUSTO,
        OS.COD_UNIDADE_EXECUTANTE, OS.DTA_HOR_FINALIZACAO DTA_OCORRENCIA, UE.NOM_UNIDADE_EXECUTANTE, OS.COD_SITUACAO_OS,
        1 QTD_OS_CONCLUIDA, 0 QTD_OS_ABERTA, 0 QTD_OS_CANCELADA, 0 QTD_OS_CONCL_EXCLUSIVA, 0 QTD_HOR_APONT,
        0 VLR_HOR_APONTAMENTO, 0 VLR_SERV_EXTO_CONTRATADO, 0 VLR_SERVICO_EXTERNO_PAGO,
        0 VLR_MATERIAL, GCC.DSC_GRUPO, GCC.COD_GRUPO,
        '' ANO_TRIAGEM, '' DTA_ABERTURA_OS, '' DTA_TRIAGEM, '' DTA_ENCERRAMENTO,
        0 QTD_DIAS_CONCLUSAO, 0 QTD_DIAS_TRIAGEM
 FROM ORDEM_SERVICO OS,  CENTRO_CUSTO CC, GRUPO_CENCUSTO GCC,
      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE
       FROM UNIDADE_EXECUTANTE
       --START WITH COD_UNIDADE_EXECUTANTE IN (2,5,6,7,8,9,11,22,70,10,25,28,29,30,34,35,39,40,78) --campus
       START WITH COD_UNIDADE_EXECUTANTE IN (23,24,43,50,51,52,79,122) --UE
       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE
 WHERE OS.DTA_HOR_FINALIZACAO BETWEEN TO_DATE('01/01/2019','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('31/12/2019','DD/MM/YYYY HH24:MI:SS') +0.9999
   AND OS.COD_SITUACAO_OS IN (4,5,6,13)
   AND OS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE
   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_GRUPO = GCC.COD_GRUPO
   AND EXISTS
     (SELECT TOS.NUM_ORDEM
      FROM TRIAGEM_ORDEM_SERVICO TOS
      WHERE TOS.NUM_ORDEM=OS.NUM_ORDEM
        AND TOS.COD_UNIDADE_EXECUTANTE=OS.COD_UNIDADE_EXECUTANTE
        AND TOS.SEQ_GRUPO_ESTATISTICA = 123)--:SEQ_GRUPO_ESTATISTICA )
 UNION ALL
 --CONCLUIDAS EXCLUSIVAMENTE NO PERÍODO
 SELECT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO NUM_OS, OS.COD_CENCUSTO, CC.NOM_CENCUSTO,
        OS.COD_UNIDADE_EXECUTANTE, OS.DTA_HOR_FINALIZACAO DTA_OCORRENCIA, UE.NOM_UNIDADE_EXECUTANTE, OS.COD_SITUACAO_OS,
        0 QTD_OS_CONCLUIDA, 0 QTD_OS_ABERTA, 0 QTD_OS_CANCELADA, 1 QTD_OS_CONCL_EXCLUSIVA, 0 QTD_HOR_APONT,
        0 VLR_HOR_APONTAMENTO, 0 VLR_SERV_EXTO_CONTRATADO, 0 VLR_SERVICO_EXTERNO_PAGO,
        0 VLR_MATERIAL, GCC.DSC_GRUPO, GCC.COD_GRUPO,
        '' ANO_TRIAGEM, '' DTA_ABERTURA_OS, '' DTA_TRIAGEM, '' DTA_ENCERRAMENTO,
        0 QTD_DIAS_CONCLUSAO, 0 QTD_DIAS_TRIAGEM
 FROM ORDEM_SERVICO OS,  CENTRO_CUSTO CC, GRUPO_CENCUSTO GCC,
      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE
       FROM UNIDADE_EXECUTANTE
       --START WITH COD_UNIDADE_EXECUTANTE IN (2,5,6,7,8,9,11,22,70,10,25,28,29,30,34,35,39,40,78) --campus
       START WITH COD_UNIDADE_EXECUTANTE IN (23,24,43,50,51,52,79,122) --UE
       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE 
 WHERE OS.DTA_CRIACAO_OS BETWEEN TO_DATE('01/01/2019','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('31/12/2019','DD/MM/YYYY HH24:MI:SS') +0.9999  
   AND OS.DTA_HOR_FINALIZACAO BETWEEN TO_DATE('01/01/2019','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('31/12/2019','DD/MM/YYYY HH24:MI:SS') +0.9999
   AND OS.COD_SITUACAO_OS IN (4,5,6,13)
   AND OS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE
   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_GRUPO = GCC.COD_GRUPO
   AND EXISTS
     (SELECT TOS.NUM_ORDEM
      FROM TRIAGEM_ORDEM_SERVICO TOS
      WHERE TOS.NUM_ORDEM=OS.NUM_ORDEM
        AND TOS.COD_UNIDADE_EXECUTANTE=OS.COD_UNIDADE_EXECUTANTE
        AND TOS.SEQ_GRUPO_ESTATISTICA = 123)--:SEQ_GRUPO_ESTATISTICA )
 UNION ALL
 -- Serviço externo CONTRATADO
 SELECT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO NUM_OS, OS.COD_CENCUSTO, CC.NOM_CENCUSTO,
        TOS.COD_UNIDADE_EXECUTANTE, DF.DTA_EMISSAO DTA_OCORRENCIA, UE.NOM_UNIDADE_EXECUTANTE, OS.COD_SITUACAO_OS,
        0 QTD_OS_CONCLUIDA, 0 QTD_OS_ABERTA, 0 QTD_OS_CANCELADA, 0 QTD_OS_CONCL_EXCLUSIVA,
        0 QTD_HOR_APONT, 0 VLR_HOR_APONTAMENTO,
        AES.VLR_CONTRATACAO VLR_SERV_EXTO_CONTRATADO, 0 VLR_SERVICO_EXTERNO_PAGO,
        0 VLR_MATERIAL, GCC.DSC_GRUPO, GCC.COD_GRUPO,
        '' ANO_TRIAGEM, '' DTA_ABERTURA_OS, '' DTA_TRIAGEM, '' DTA_ENCERRAMENTO,
        0 QTD_DIAS_CONCLUSAO, 0 QTD_DIAS_TRIAGEM
 FROM DOCUMENTO_FINANCEIRO DF, AGENDA_AUT_ENTREGA_SERVICO AGS, AUTORIZACAO_ENTREGA_SERVICO AES, COTACAO_PEDIDO_SERVICO CPS,
      PEDIDO_SERVICO PS, TRIAGEM_ORDEM_SERVICO TOS, ORDEM_SERVICO OS, GRUPO_CENCUSTO GCC,
       CENTRO_CUSTO CC,
      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE
       FROM UNIDADE_EXECUTANTE
       --START WITH COD_UNIDADE_EXECUTANTE IN (2,5,6,7,8,9,11,22,70,10,25,28,29,30,34,35,39,40,78) --campus
       START WITH COD_UNIDADE_EXECUTANTE IN (23,24,43,50,51,52,79,122) --UE
       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE
 WHERE DF.DTA_EMISSAO BETWEEN TO_DATE('01/01/2019','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('31/12/2019','DD/MM/YYYY HH24:MI:SS') +0.9999
   AND DF.NUM_DOC_FINANCEIRO=AGS.NUM_DOC_FINANCEIRO
   AND AGS.NUM_AUT_ENTREGA_SERVICO=AES.NUM_AUT_ENTREGA_SERVICO
   AND AES.NUM_COTACAO_SERVICO=CPS.NUM_COTACAO_SERVICO
   AND CPS.NUM_PEDIDO_SERVICO=PS.NUM_PEDIDO_SERVICO
   AND PS.NUM_TRIAGEM_OS=TOS.NUM_TRIAGEM_OS
   AND TOS.NUM_ORDEM=OS.NUM_ORDEM
   AND OS.COD_SITUACAO_OS IN (4,5,6,13)
   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_GRUPO = GCC.COD_GRUPO
   AND TOS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE
   AND TOS.SEQ_GRUPO_ESTATISTICA = 123--:SEQ_GRUPO_ESTATISTICA
 UNION ALL
 -- Custo dos materiais Gastos, com base no custo médio
 SELECT OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO||'/'||OS.ANO_ORDEM_SERVICO NUM_OS, OS.COD_CENCUSTO, CC.NOM_CENCUSTO,
        TOS.COD_UNIDADE_EXECUTANTE, IRM.DTA_MOV_CONTABIL DTA_OCORRENCIA, UE.NOM_UNIDADE_EXECUTANTE, OS.COD_SITUACAO_OS,
        0 QTD_OS_CONCLUIDA, 0 QTD_OS_ABERTA, 0 QTD_OS_CANCELADA, 0 QTD_OS_CONCL_EXCLUSIVA, 0 QTD_HOR_APONT,
        0 VLR_HOR_APONTAMENTO, 0 VLR_SERV_EXTO_CONTRATADO, 0 VLR_SERVICO_EXTERNO_PAGO,
        SUM(IRM.VLR_PONDERADO*IRM.QTD_FORNE_RECEBIDA*DECODE(RM.IDF_TIPO_REQUISICAO,0,1,1,-1,0)) VLR_MATERIAL,
        GCC.DSC_GRUPO, GCC.COD_GRUPO,
        '' ANO_TRIAGEM, '' DTA_ABERTURA_OS, '' DTA_TRIAGEM, '' DTA_ENCERRAMENTO,
        0 QTD_DIAS_CONCLUSAO, 0 QTD_DIAS_TRIAGEM
 FROM ITEM_REQUISICAO_MATERIAL IRM, REQUISICAO_MATERIAL RM, COMPLEMENTO_REQUISICAO CR,
      TRIAGEM_ORDEM_SERVICO TOS, ORDEM_SERVICO OS, GRUPO_CENCUSTO GCC,
       CENTRO_CUSTO CC,
      (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE
       FROM UNIDADE_EXECUTANTE
       --START WITH COD_UNIDADE_EXECUTANTE IN (2,5,6,7,8,9,11,22,70,10,25,28,29,30,34,35,39,40,78) --campus
       START WITH COD_UNIDADE_EXECUTANTE IN (23,24,43,50,51,52,79,122) --UE
       CONNECT BY PRIOR  COD_UNIDADE_EXECUTANTE=COD_UNIDADE_EXECUTANTE_PAI) UE
 WHERE IRM.DTA_MOV_CONTABIL BETWEEN  TO_DATE('01/01/2019','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('31/12/2019','DD/MM/YYYY HH24:MI:SS') +0.9999
   AND IRM.NUM_REQUISICAO=RM.NUM_REQUISICAO
   AND IRM.ANO_REQUISICAO_MATERIAL=RM.ANO_REQUISICAO_MATERIAL
   AND RM.ANO_REQUISICAO_MATERIAL=CR.ANO_REQUISICAO_MATERIAL
   AND RM.NUM_REQUISICAO=CR.NUM_REQUISICAO
   AND CR.IDF_TIPO_DOCUMENTO=17
   AND CR.NUM_DOCUMENTO=TOS.NUM_TRIAGEM_OS
   AND TOS.NUM_ORDEM=OS.NUM_ORDEM
   AND OS.COD_SITUACAO_OS IN (4,5,6,13)
   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_GRUPO = GCC.COD_GRUPO
   AND TOS.COD_UNIDADE_EXECUTANTE=UE.COD_UNIDADE_EXECUTANTE
   AND TOS.SEQ_GRUPO_ESTATISTICA = 123--:SEQ_GRUPO_ESTATISTICA
 GROUP BY OS.NUM_ORDEM, OS.NUM_ORDEM_SERVICO, OS.ANO_ORDEM_SERVICO, OS.COD_CENCUSTO, GCC.DSC_GRUPO, GCC.COD_GRUPO,
          TOS.COD_UNIDADE_EXECUTANTE, IRM.DTA_MOV_CONTABIL, UE.NOM_UNIDADE_EXECUTANTE, OS.COD_SITUACAO_OS, CC.NOM_CENCUSTO
) X
 GROUP BY X.COD_CENCUSTO, X.NOM_CENCUSTO, X.DSC_GRUPO--, X.COD_GRUPO, X.NOM_UNIDADE_EXECUTANTE, X.COD_UNIDADE_EXECUTANTE
) W
GROUP BY W.DSC_GRUPO
ORDER BY W.DSC_GRUPO;
