 SELECT --COD_INSTITUTO,
        INS.NOM_INSTITUTO,
        CCBP.COD_CENCUSTO,
        CC.NOM_CENCUSTO,
        NUM_BEM,
        M.NOM_MATERIAL,
        BP.DSC_COMPLEMENTAR,
        NUM_INCORPORACAO,
        BP.NUM_PATRIMONIO,
        TP.DSC_TIPO_PATRIMONIO
 FROM CENTRO_CUSTO_BEM_PATRIMONIAL CCBP
 INNER JOIN CENTRO_CUSTO CC ON CC.COD_CENCUSTO = CCBP.COD_CENCUSTO
 JOIN INSTITUTO INS USING (COD_INSTITUTO)
 INNER JOIN BEM_PATRIMONIAL BP USING(NUM_BEM)
JOIN TIPO_PATRIMONIO TP USING(COD_TIPO_PATRIMONIO)
 LEFT JOIN INCORPORACAO I USING(NUM_INCORPORACAO)
 JOIN MATERIAL M USING(COD_MATERIAL)
 WHERE CCBP.DTA_FIM IS NULL
 AND CC.COD_CENCUSTO = 'CCEA0001X'
 ORDER BY COD_CENCUSTO;
 ---------------------------------
 SELECT COD_CENCUSTO,
       CC.NOM_CENCUSTO,
       COUNT(*) QTD
 FROM CENTRO_CUSTO_BEM_PATRIMONIAL CCBP
 INNER JOIN CENTRO_CUSTO CC USING (COD_CENCUSTO)
 WHERE CCBP.DTA_FIM IS NULL
 GROUP BY COD_CENCUSTO,
          CC.NOM_CENCUSTO
 ORDER BY QTD DESC
