SELECT CC.COD_CENCUSTO,
       CC.NOM_CENCUSTO,
       L.SGL_LOCAL UNID_ADM,
       SUM(X.VLR_PROGRAMACAO * FCN_VLR_UNIT_PROGRAMACAO(M.COD_MATERIAL, 1) *  DECODE(M.IDF_ATIVO, 'S', 1, 0)) VLR_PROGRAMACAO,
       SUM(X.VLR_CONSU_GERAL * FCN_VLR_UNIT_PROGRAMACAO(M.COD_MATERIAL, 1)) VLR_CONSU_GERAL,
       SUM(CASE WHEN (G.COD_ALINEA NOT IN (12, 14, 15, 16, 21) AND M.IDF_CODIGO_GENERICO = 'N') THEN
              X.VLR_CONSU_GERAL * FCN_VLR_UNIT_PROGRAMACAO(M.COD_MATERIAL, 1)
             ELSE 0 END) VLR_CONSU_MATERIAL,
       SUM(CASE  WHEN (G.COD_ALINEA = 16 AND M.IDF_CODIGO_GENERICO = 'N') THEN
              X.VLR_CONSU_GERAL * FCN_VLR_UNIT_PROGRAMACAO(M.COD_MATERIAL, 1)
             ELSE 0 END) VLR_CONSU_MEDICAMENTO,
       SUM(CASE WHEN (G.COD_ALINEA IN (12, 14, 15, 21)) OR (M.IDF_CODIGO_GENERICO = 'S') THEN
              X.VLR_CONSU_GERAL * FCN_VLR_UNIT_PROGRAMACAO(M.COD_MATERIAL, 1)
             ELSE 0 END) VLR_CONSU_OUTROS,
       SUM(DECODE(M.IDF_CODIGO_GENERICO, 'S', 0, 1) * X.VLR_CONSU_PROGRAMACAO *
           FCN_VLR_UNIT_PROGRAMACAO(M.COD_MATERIAL, 1)) VLR_CONSU_PROGRAMACAO,
       SUM(DECODE(M.IDF_CODIGO_GENERICO, 'S', 0, 1) * X.VLR_DISPENSADO * FCN_VLR_UNIT_PROGRAMACAO(M.COD_MATERIAL, 1)) VLR_DISPENSADO
  FROM (SELECT COD_CENCUSTO,
               COD_MATERIAL,
               SUM(QTD_PROGRAMADA_ANO) VLR_PROGRAMACAO,
               SUM(QTD_CONSUMIDA) VLR_CONSU_GERAL,
               SUM(QTD_CONSU_PROGRAMACAO) VLR_CONSU_PROGRAMACAO,
               SUM(QTD_DISPENSADA) VLR_DISPENSADO
          FROM (SELECT PM.COD_CENCUSTO,
                       PM.COD_MATERIAL,
                       PM.QTD_PROGRAMADA_ANO,
                       0                     QTD_CONSUMIDA,
                       0                     QTD_CONSU_PROGRAMACAO,
                       0                     QTD_DISPENSADA
                  FROM PROGRAMACAO_MATERIAL PM, CENTRO_CUSTO CC, INSTITUTO I
                 WHERE PM.COD_CENCUSTO = CC.COD_CENCUSTO
                   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
                   AND I.COD_INST_SISTEMA = 1
                   AND PM.ANO_PROGRAMACAO = 2023
                
                UNION ALL
                SELECT CM.COD_CENCUSTO,
                       CM.COD_MATERIAL,
                       0 QTD_PROGRAMADA_ANO,
                       CM.QTD_CONSUMIDA,
                       CM.QTD_CONSU_PROGRAMACAO,
                       CM.QTD_DISPENSADA
                  FROM CONSUMO_MENSAL_MATERIAL CM,
                       CENTRO_CUSTO            CC,
                       INSTITUTO               I
                 WHERE CM.COD_CENCUSTO = CC.COD_CENCUSTO
                   AND CC.COD_INSTITUTO = I.COD_INSTITUTO
                   AND I.COD_INST_SISTEMA = 1
                   AND CM.NUM_ANO = 2023
                
                )
         GROUP BY COD_CENCUSTO, COD_MATERIAL) X,
       CENTRO_CUSTO CC,
       MATERIAL M,
       GRUPO G,
       LOCAL L,
       ALINEA AL
 WHERE X.COD_CENCUSTO = CC.COD_CENCUSTO
   AND X.COD_MATERIAL = M.COD_MATERIAL
   AND M.COD_GRUPO = G.COD_GRUPO
   AND G.COD_ALINEA = AL.COD_ALINEA
   AND CC.COD_LOCAL = L.COD_LOCAL(+)
 GROUP BY CC.COD_CENCUSTO, CC.NOM_CENCUSTO, L.SGL_LOCAL

 ORDER BY CC.COD_CENCUSTO
