/*CHECAR EXISTENCIA DAS SEQUENCES*/
select sequence_owner, sequence_name from dba_sequences ds
WHERE ds.SEQUENCE_OWNER = 'DOCUMENTO'
AND ds.SEQUENCE_NAME LIKE '%BAURU%';

/*CRIAR REFERENCIAS DAS SEQUENCES NAS ESPECIES*/
SELECT DISTINCT I.NOM_SEQUENCE_DOCUMENTO
  FROM INSTITUICAO_ESPECIE_DOCUMENTO I
 WHERE I.COD_INSTITUICAO = 65
   AND I.NOM_SEQUENCE_DOCUMENTO <> 'SEQ_NUM_DOCUMENTO';
   
   
/*PARAMETRIZAR SEQUENCES PARA ZERAR ANUALMENTE*/
SELECT * FROM sequences_hcrp sh
WHERE sh.sequence_name LIKE '%BAURU%';
