SELECT ML.NOM_LOCAL,
       COUNT(*) QTD
 FROM mapeamento_local ml
 WHERE ML.COD_CENCUSTO IS NOT NULL
 GROUP BY ML.NOM_LOCAL
 HAVING COUNT(*) > 2
 ORDER BY QTD DESC;
 
 
 SELECT ML.COD_CENCUSTO,
        (SELECT CC.NOM_CENCUSTO
         FROM CENTRO_CUSTO CC
         WHERE CC.COD_CENCUSTO = ML.COD_CENCUSTO) NOM_CENCUSTO,
       COUNT(*) QTD
 FROM mapeamento_local ml
 WHERE ML.COD_CENCUSTO IS NOT NULL
 GROUP BY ML.COD_CENCUSTO
 HAVING COUNT(*) > 2
 ORDER BY QTD DESC;
 -------------------
--BALCAO 02;
;
SELECT *
 FROM mapeamento_local ml
 WHERE 1 = 1
 --AND ML.COD_CENCUSTO = 'CACC08029';
 AND  ML.COD_CENCUSTO = 'HEAB00033';

SELECT *
 FROM CENTRO_CUSTO CC
 WHERE CC.COD_CENCUSTO = 'CACC0002X';
