/*Daniel Anselmo*/
SELECT  P.CHAVE
       ,P.PATRIMONIO_ATUAL
       ,TP.DSC_TIPO_PATRIMONIO TIPO_PATRIMONIO
       ,COD_MATERIAL
       ,MT.NOM_MATERIAL
       ,BP.DSC_COMPLEMENTAR
       ,P.PATRIMONIOS_POR_CHAVE
       ,P.QTD
       ,NVL(MT.TAX_DEPRECIACAO_ANUAL, SG.TAX_DEPRECIACAO_ANUAL) TAX_DEPRECIACAO_ANUAL
       ,IC.DTA_HOR_INCORPORACAO
       ,BP.DTA_DESINCORPORACAO
       ,L.DSC_LOCALIZACAO
       ,CCBP.COD_CENCUSTO
       ,CC.NOM_CENCUSTO CENTRO_CUSTO_ATUAL
       ,DECODE(BP.IDF_ESTADO_BEM,0,'INDEFINIDO',1,'BOM',2,'REGULAR',3, 'MAU',4, 'SUCATA') IDF_ESTADO_BEM
       ,BP.CPL_LOCALIZACAO
       ,IC.VLR_TOTAL_ITEM / NVL(IC.QTD_INCORPORADA, 1) VLR_BEM
       ,NVL(CTA.COD_CONTABIL || ' - ' || CTA.DSC_CONTABIL, '') AS CONTA_CONTABIL
       ,IC.DTA_INCORPORACAO_CONTABIL DATA_CONTABILIZACAO
       ,BP.DTA_DESINCORPORACAO_CONTABIL
FROM BEM_PATRIMONIAL BP
LEFT JOIN CENTRO_CUSTO_BEM_PATRIMONIAL CCBP ON CCBP.NUM_BEM = BP.NUM_BEM
   AND CCBP.DTA_FIM IS NULL
JOIN LOCALIZACAO L ON L.COD_LOCALIZACAO = CCBP.COD_LOCALIZACAO
JOIN CENTRO_CUSTO CC ON CC.COD_CENCUSTO = CCBP.COD_CENCUSTO
   AND CC.COD_INSTITUTO in (1, 2, 3, 4, 5)
JOIN TIPO_PATRIMONIO TP USING(COD_TIPO_PATRIMONIO) 
LEFT JOIN INCORPORACAO IC USING(NUM_INCORPORACAO)
LEFT JOIN CONTA_CONTABIL CTA USING(COD_CONTA)
LEFT JOIN MATERIAL MT USING(COD_MATERIAL)
JOIN SUB_GRUPO SG 
   ON SG.COD_GRUPO = MT.COD_GRUPO
   AND MT.COD_SUB_GRUPO = SG.COD_SUB_GRUPO
LEFT JOIN (SELECT  NP.NUM_BEM CHAVE,
              (SELECT A.NUM_PATRIMONIO
                  FROM BEM_PATRIMONIAL A WHERE A.NUM_BEM = NP.NUM_BEM) PATRIMONIO_ATUAL
             ,(SELECT TP.DSC_TIPO_PATRIMONIO
                 FROM  TIPO_PATRIMONIO TP
                 WHERE TP.COD_TIPO_PATRIMONIO = BP.COD_TIPO_PATRIMONIO) TIPO_PATRIMONIO
             ,RTRIM(XMLAGG(XMLELEMENT(E, NP.NUM_PATRIMONIO||'-'||TP.DSC_TIPO_PATRIMONIO, ',' || CHR(13)).EXTRACT('//text()') ORDER BY NP.NUM_PATRIMONIO)
                              .GETCLOBVAL(),  ',') PATRIMONIOS_POR_CHAVE
             ,COUNT(*) QTD
FROM NUMERO_PATRIMONIO NP
LEFT JOIN BEM_PATRIMONIAL BP ON BP.NUM_BEM = NP.NUM_BEM
JOIN TIPO_PATRIMONIO TP ON TP.COD_TIPO_PATRIMONIO = NP.COD_TIPO_PATRIMONIO
GROUP BY NP.NUM_BEM, BP.COD_TIPO_PATRIMONIO ) P
   ON P.CHAVE = BP.NUM_BEM
   AND P.PATRIMONIO_ATUAL = BP.NUM_PATRIMONIO
WHERE IC.DTA_HOR_INCORPORACAO BETWEEN NVL(TO_DATE('01/04/1956', 'DD/MM/YYYY'), IC.DTA_HOR_INCORPORACAO)
AND NVL(TO_DATE('31/12/2022', 'DD/MM/YYYY'), IC.DTA_HOR_INCORPORACAO)
AND P.CHAVE IN (5, 13, 16, 29, 31, 228, 1157, 1493)
ORDER BY  NOM_MATERIAL, NUM_PATRIMONIO;
--------------------------------------------------------------------------------

SELECT *
 FROM bem_patrimonial NP
 WHERE NP.NUM_BEM IN (5, 13, 16, 29, 31, 228, 1157, 1493);

SELECT *
 FROM instituto i
 WHERE i.cod_inst_sistema = 1;
