--DEIVID GUILHERME DOS SANTOS SANTANA
--0612273I

--0564558I
SELECT B.NUM_SOLIC_REL_MEDICO, B.COD_DEPARTAMENTO, B.COD_ESPECIALIDADE,
   C.NOM_PACIENTE ||' ' || C.SBN_PACIENTE NOME_PACIENTE,  C.NOM_SOCIAL, C.COD_PACIENTE,
   D.NOM_DEPARTAMENTO, E.NOM_ESPECIALIDADE, B.DTA_ATENDIMENTO_INICIAL,
   B.DSC_TRATAMENTO_CLINICO, B.DSC_TRATAMENTO_CIRURGICO,
   B.DSC_INFORMACOES_RELEVANTES, B.DTA_RELATORIO_MEDICO,
   F.NUM_DOC_PROFISSIONAL, F.NOM_PROFISSIONAL || ' ' || F.SBN_PROFISSIONAL NOME_PROFISSIONAL,
   B.SEQ_REL_MEDICO
FROM SOLICITACAO_REL_MEDICO A, RELATORIO_MEDICO B, PACIENTE C, DEPARTAMENTO D, ESPECIALIDADE E, PROFISSIONAL F
WHERE B.SEQ_REL_MEDICO = 268871
  AND B.NUM_SOLIC_REL_MEDICO = A.NUM_SOLIC_REL_MEDICO
  AND C.COD_PACIENTE = A.COD_PACIENTE
  AND D.COD_DEPARTAMENTO = B.COD_DEPARTAMENTO
  AND E.COD_ESPECIALIDADE = B.COD_ESPECIALIDADE
  AND F.COD_PROFISSIONAL = B.COD_PROFISSIONAL;
  --------------------------------------------
  SELECT A.NUM_SOLIC_REL_MEDICO, B.NOM_PACIENTE || ' ' || B.SBN_PACIENTE || ' - ' || B.COD_PACIENTE DSC_INTERESSADO,
       DECODE(B.Nom_Social, NULL, '', 'Nome social:  '||B.Nom_Social) NOM_SOCIAL,
       B.NOM_MAE || DECODE(B.NOM_PAI, NULL,'',' e ' || B.NOM_PAI) FILIACAO,
       B.SGL_TIPO_DOCUMENTO || ' ' || B.NUM_DOC_PACIENTE || ' DN. ' || TO_CHAR(B.DTA_NASCIMENTO,'DD/MM/YYYY') DOCUMENTO,
       B.DSC_TIPO_LOGRADOURO || ' ' || B.DSC_ENDERECO || ' ' || B.NUM_ENDERECO || ' ' || B.CPL_ENDERECO || ' CEP - ' || TRIM(B.CEP_PACIENTE)||' TEL '||B.num_telefone||' E-mail '|| B.dsc_email ENDERECO_PACIENTE,
       DECODE(C.COD_PACIENTE,NULL, TRIM(B.DSC_TIPO_LOGRADOURO) || ' ' || TRIM(B.DSC_ENDERECO) || ' ' || TRIM(B.NUM_ENDERECO) || ' ' || TRIM(B.CPL_ENDERECO)  || ' CEP - ' || TRIM(B.CEP_PACIENTE),
              TRIM(G.ABV_TIPO_LOGRADOURO) || ' ' || TRIM(C.DSC_END) || ' ' || TRIM(C.NUM_END) || ' ' || TRIM(C.DSC_COMPLEMENTO) || ' CEP - ' || TRIM(C.NUM_CEP)) ENDERECO_CORRESPONDENCIA,
       TRIM(B.NOM_BAIRRO) BAIRRO_PACIENTE,
       DECODE(C.COD_PACIENTE, NULL, B.NOM_BAIRRO, C.DSC_BAIRRO) BAIRRO_CORRESPONDENCIA,
       DECODE(B.NOM_CIDADE,NULL,TRIM(D.NOM_LOCALIDADE),B.NOM_CIDADE) || ' - ' || TRIM(B.IDF_ESTADO) CIDADE_PACIENTE,
       DECODE(C.COD_PACIENTE, NULL, DECODE(B.NOM_CIDADE, NULL, TRIM(D.NOM_LOCALIDADE),B.NOM_CIDADE) || ' - ' || TRIM(B.IDF_ESTADO), TRIM(E.NOM_LOCALIDADE) || ' - ' || TRIM(C.SGL_UF)) CIDADE_CORRESPONDENCIA,
       TRIM(A.DSC_COMPL_SOLICITACAO) || ' ' || DECODE(TRIM(F.DSC_MOTIVO_SOLICITACAO),'OUTROS','',TRIM(F.DSC_MOTIVO_SOLICITACAO)) MOTIVO_SOLICITACAO,
       TO_CHAR(A.DTA_SOLICITACAO,'DD/MM/YYYY HH24:MI:SS') DTA_SOLICITACAO,
       A.NUM_SOLIC_REL_MEDICO NUM_REQUERIMENTO,
       CASE WHEN A.IDF_RETIRADA = 0 THEN 'Autorizo o envio por carta simples, mesmo ciente que esta pode vir a ser recebida por terceiro.'
            WHEN A.IDF_RETIRADA = 1 THEN 'Virá retirar.'
            WHEN A.IDF_RETIRADA = 2 THEN 'Autorizo '||A.DSC_COMPL_RETIRADA||' a retirar.'  
            WHEN A.IDF_RETIRADA = 3 THEN 'Autorizo que as informações solicitadas sejam encaminhadas por via eletrônica, através do e-mail '||A.DSC_COMPL_RETIRADA||', que é de meu uso exclusivo.'
       END DSC_RETIRADA,
       A.IDF_TIPO_SOLICITACAO
FROM SOLICITACAO_REL_MEDICO A, PACIENTE B, PACIENTE_END_CORRESPONDENCIA C, LOCALIDADE D, LOCALIDADE E,
     MOTIVO_SOLICITACAO F, TIPO_LOGRADOURO G
WHERE A.NUM_SOLIC_REL_MEDICO = 309193--:NUM_SOLIC_REL_MEDICO
  AND A.COD_PACIENTE = B.COD_PACIENTE
  AND C.COD_PACIENTE(+) = B.COD_PACIENTE
  AND D.COD_LOCALIDADE(+) = B.COD_LOCALIDADE
  AND E.COD_LOCALIDADE(+) = C.COD_LOCALIDADE
  AND G.COD_TIPO_LOGRADOURO(+) = C.TIP_LOGRADOURO
  AND F.COD_MOTIVO_SOLICITACAO = A.COD_MOTIVO_SOLICITACAO;
 
 
 

  
  SELECT B.DSC_TIPO_LOGRADOURO || ' ' || B.DSC_ENDERECO || ' ' || B.NUM_ENDERECO || ' ' || B.CPL_ENDERECO || ' CEP - ' || TRIM(B.CEP_PACIENTE)||' TEL '||B.num_telefone||' E-mail '|| B.dsc_email ENDERECO_PACIENTE,
         B.DSC_TIPO_LOGRADOURO || ' ' || B.DSC_ENDERECO || ' ' || B.NUM_ENDERECO || ' ' || B.CPL_ENDERECO || ' CEP - ' || TRIM(B.CEP_PACIENTE)||DECODE(B.num_telefone, NULL, NULL, ' TEL '||B.NUM_TELEFONE)||
         DECODE(B.DSC_EMAIL, NULL, NULL, ' EMAIL '||B.DSC_EMAIL) ENDERECO_PACIENTE
   FROM paciente b
   WHERE b.cod_paciente = '0564558I';
   --'0612273I';
   
    SELECT p.num_telefone, p.dsc_email
      FROM paciente p;
   
  SELECT *
   FROM SOLICITACAO_REL_MEDICO A
   WHERE A.Cod_Paciente = '0612273I';
  ------------------------------------------------
  SELECT A.NUM_SOLIC_REL_MEDICO, A.NUM_DOCUMENTO, A.ANO_DOCUMENTO,
   A.NUM_DOCUMENTO || '/' || A.ANO_DOCUMENTO DOCUMENTO,
	B.DSC_MOTIVO_SOLICITACAO, A.DTA_SOLICITACAO,
   C.NOM_PACIENTE || ' ' || C.SBN_PACIENTE PACIENTE,
   A.IDF_STATUS, C.COD_PACIENTE, ED.DSC_ESPECIE
FROM SOLICITACAO_REL_MEDICO A, MOTIVO_SOLICITACAO B, PACIENTE C, ESPECIE_DOCUMENTO ED
WHERE A.NUM_DOCUMENTO = 1499
  AND A.ANO_DOCUMENTO = 2023
  AND A.COD_ESPECIE = 40
  AND A.IDF_STATUS IN ('1','2')

  AND A.IDF_TIPO_SOLICITACAO IN ('R','M')

  AND A.COD_MOTIVO_SOLICITACAO = B.COD_MOTIVO_SOLICITACAO
  AND A.COD_PACIENTE = C.COD_PACIENTE
  AND A.COD_ESPECIE = ED.COD_ESPECIE
  AND A.DTA_SOLICITACAO >= (SYSDATE - 180);         --considerar Requerimentos abertos nos ultimos 6 meses (conforme OS 18606/2016)

 

 SELECT TRUNC(SYSDATE) - to_date('04/07/2022 ','DD/MM/YYYY') resultado  FROM dual;
 
 
