SELECT *
 FROM sistema s;
 
 SELECT *
  FROM pesquisa_sistema ps
  WHERE ps.cod_sistema = 62
  AND ps.cod_pesquisa = 1836
  FOR UPDATE;
  
  --Relatórios Médicos solicitados no período - cálculo automático
  ----------------------------------------------------------------
  SELECT DATA, SUM(QTD_RELATORIO) QTD_RELATORIO_MEDICO, SUM(QTD_EXAME) QTD_CAT_EXAME, SUM(QTD_PRONTUARIO) QTD_COPIA_PRONTUARIO, SUM(QTD_ATESTADO) QTD_ATESTADO, SUM(QTD_DPVAT) QTD_DPVAT
FROM (
    SELECT 
      TO_CHAR(A.DTA_SOLICITACAO, 'DD/MM/YYYY') DATA,
      (SELECT COUNT(1) FROM MOTIVO_SOLICITACAO M WHERE M.COD_MOTIVO_SOLICITACAO = A.COD_MOTIVO_SOLICITACAO AND UPPER(A.DSC_COMPL_SOLICITACAO) LIKE '%RELAT%') QTD_RELATORIO,
      (SELECT COUNT(1) FROM MOTIVO_SOLICITACAO M WHERE M.COD_MOTIVO_SOLICITACAO = A.COD_MOTIVO_SOLICITACAO              
              AND ((M.DSC_MOTIVO_SOLICITACAO LIKE UPPER( '%EXAME%' ) OR UPPER(A.DSC_COMPL_SOLICITACAO) LIKE '%EXAME%')
                   OR M.DSC_MOTIVO_SOLICITACAO LIKE UPPER( '%LAUDO%' ) OR UPPER(A.DSC_COMPL_SOLICITACAO) LIKE '%LAUDO%')
      ) QTD_EXAME,  
      (SELECT COUNT(1) FROM MOTIVO_SOLICITACAO M WHERE M.COD_MOTIVO_SOLICITACAO = A.COD_MOTIVO_SOLICITACAO AND UPPER(A.DSC_COMPL_SOLICITACAO) LIKE '%PRONTU%') QTD_PRONTUARIO,
      (SELECT COUNT(1) FROM MOTIVO_SOLICITACAO M WHERE M.COD_MOTIVO_SOLICITACAO = A.COD_MOTIVO_SOLICITACAO AND UPPER(A.DSC_COMPL_SOLICITACAO) LIKE '%ATESTADO%') QTD_ATESTADO,
      (SELECT COUNT(1) FROM MOTIVO_SOLICITACAO M WHERE M.COD_MOTIVO_SOLICITACAO = A.COD_MOTIVO_SOLICITACAO AND UPPER(M.DSC_MOTIVO_SOLICITACAO) LIKE '%DPVAT%') QTD_DPVAT
    FROM 
      SOLICITACAO_REL_MEDICO A, INSTITUICAO B, ESPECIE_DOCUMENTO C
    WHERE 
     -- TRUNC(A.DTA_SOLICITACAO) BETWEEN :DATA_INICIO AND :DATA_FIM
     TRUNC(A.DTA_SOLICITACAO) BETWEEN to_date('01/06/2022', 'DD/MM/YYYY') AND to_date('01/07/2022', 'DD/MM/YYYY')
      AND A.COD_INSTITUICAO = B.COD_INSTITUICAO
      AND A.COD_ESPECIE = C.COD_ESPECIE
)
GROUP BY DATA     
ORDER BY 1; 
