SELECT B.NUM_SOLIC_REL_MEDICO, B.COD_DEPARTAMENTO, B.COD_ESPECIALIDADE,
   C.NOM_PACIENTE ||' ' || C.SBN_PACIENTE NOME_PACIENTE,  C.NOM_SOCIAL, C.COD_PACIENTE,
   D.NOM_DEPARTAMENTO, E.NOM_ESPECIALIDADE, B.DTA_ATENDIMENTO_INICIAL,
   B.DSC_TRATAMENTO_CLINICO, B.DSC_TRATAMENTO_CIRURGICO,
   B.DSC_INFORMACOES_RELEVANTES, B.DTA_RELATORIO_MEDICO,
   F.NUM_DOC_PROFISSIONAL, F.NOM_PROFISSIONAL || ' ' || F.SBN_PROFISSIONAL NOME_PROFISSIONAL,
   B.SEQ_REL_MEDICO
FROM SOLICITACAO_REL_MEDICO A, RELATORIO_MEDICO B, PACIENTE C, DEPARTAMENTO D, ESPECIALIDADE E, PROFISSIONAL F
WHERE B.SEQ_REL_MEDICO = 269693
  AND B.NUM_SOLIC_REL_MEDICO = A.NUM_SOLIC_REL_MEDICO
  AND C.COD_PACIENTE = A.COD_PACIENTE
  AND D.COD_DEPARTAMENTO = B.COD_DEPARTAMENTO
  AND E.COD_ESPECIALIDADE = B.COD_ESPECIALIDADE
  AND F.COD_PROFISSIONAL = B.COD_PROFISSIONAL;
--------------------------------------------------------------------------------------------
SELECT COD_PACIENTE, NOM_PACIENTE, NOM_SOCIAL,SBN_PACIENTE,
DTA_NASCIMENTO, DECODE(IDF_COR,1,'BRANCO',2,'PRETO',3,'AMARELO',4,'VERMELLHO',5,'MULATO','  ') IDF_COR,
DECODE(IDF_SEXO,'M','MASCULINO','F','FEMININO','D','DESCONHECIDO','  ') IDF_SEXO,
NUM_DOC_PACIENTE, NOM_MAE, CEP_PACIENTE, NOM_CIDADE, IDF_ESTADO, NOM_BAIRRO, DSC_TIPO_LOGRADOURO,
DSC_ENDERECO, NUM_ENDERECO, CPL_ENDERECO
FROM PACIENTE
WHERE COD_PACIENTE = '1188254B'; 
--------------------------------------------------------------------------------------------
SELECT A.NUM_SOLIC_REL_MEDICO, B.NOM_PACIENTE || ' ' || B.SBN_PACIENTE || ' - ' || B.COD_PACIENTE DSC_INTERESSADO,
       DECODE(B.Nom_Social, NULL, '', 'Nome social:  '||B.Nom_Social) NOM_SOCIAL,
       B.NOM_MAE || DECODE(B.NOM_PAI, NULL,'',' e ' || B.NOM_PAI) FILIACAO,
       B.SGL_TIPO_DOCUMENTO || ' ' || B.NUM_DOC_PACIENTE || ' DN. ' || TO_CHAR(B.DTA_NASCIMENTO,'DD/MM/YYYY') DOCUMENTO,
       B.DSC_TIPO_LOGRADOURO || ' ' || B.DSC_ENDERECO || ' ' || B.NUM_ENDERECO || ' ' || B.CPL_ENDERECO || ' CEP - ' || TRIM(B.CEP_PACIENTE) ENDERECO_PACIENTE,
       DECODE(C.COD_PACIENTE,NULL, TRIM(B.DSC_TIPO_LOGRADOURO) || ' ' || TRIM(B.DSC_ENDERECO) || ' ' || TRIM(B.NUM_ENDERECO) || ' ' || TRIM(B.CPL_ENDERECO)  || ' CEP - ' || TRIM(B.CEP_PACIENTE),
              TRIM(G.ABV_TIPO_LOGRADOURO) || ' ' || TRIM(C.DSC_END) || ' ' || TRIM(C.NUM_END) || ' ' || TRIM(C.DSC_COMPLEMENTO) || ' CEP - ' || TRIM(C.NUM_CEP)) ENDERECO_CORRESPONDENCIA,
       TRIM(B.NOM_BAIRRO) BAIRRO_PACIENTE,
       DECODE(C.COD_PACIENTE, NULL, B.NOM_BAIRRO, C.DSC_BAIRRO) BAIRRO_CORRESPONDENCIA,
       DECODE(B.NOM_CIDADE,NULL,TRIM(D.NOM_LOCALIDADE),B.NOM_CIDADE) || ' - ' || TRIM(B.IDF_ESTADO) CIDADE_PACIENTE,
       DECODE(C.COD_PACIENTE, NULL, DECODE(B.NOM_CIDADE, NULL, TRIM(D.NOM_LOCALIDADE),B.NOM_CIDADE) || ' - ' || TRIM(B.IDF_ESTADO), TRIM(E.NOM_LOCALIDADE) || ' - ' || TRIM(C.SGL_UF)) CIDADE_CORRESPONDENCIA,
       TRIM(A.DSC_COMPL_SOLICITACAO) || ' ' || DECODE(TRIM(F.DSC_MOTIVO_SOLICITACAO),'OUTROS','',TRIM(F.DSC_MOTIVO_SOLICITACAO)) MOTIVO_SOLICITACAO,
       TO_CHAR(A.DTA_SOLICITACAO,'DD/MM/YYYY HH24:MI:SS') DTA_SOLICITACAO,
       A.NUM_SOLIC_REL_MEDICO NUM_REQUERIMENTO,
       CASE WHEN A.IDF_RETIRADA = 0 THEN 'Autorizo o envio por carta simples, mesmo ciente que esta pode vir a ser recebida por terceiro.'
            WHEN A.IDF_RETIRADA = 1 THEN 'Virá retirar.'
            WHEN A.IDF_RETIRADA = 2 THEN 'Autorizo '||A.DSC_COMPL_RETIRADA||' a retirar.'  
            WHEN A.IDF_RETIRADA = 3 THEN 'Autorizo que as informações solicitadas sejam encaminhadas por via eletrônica, através do e-mail '||A.DSC_COMPL_RETIRADA||', que é de meu uso exclusivo.'
       END DSC_RETIRADA,
       A.IDF_TIPO_SOLICITACAO 
FROM SOLICITACAO_REL_MEDICO A, PACIENTE B, PACIENTE_END_CORRESPONDENCIA C, LOCALIDADE D, LOCALIDADE E,
     MOTIVO_SOLICITACAO F, TIPO_LOGRADOURO G
WHERE A.NUM_SOLIC_REL_MEDICO = 310509--310509--:NUM_SOLIC_REL_MEDICO
  AND A.COD_PACIENTE = B.COD_PACIENTE
  AND C.COD_PACIENTE(+) = B.COD_PACIENTE
  AND D.COD_LOCALIDADE(+) = B.COD_LOCALIDADE
  AND E.COD_LOCALIDADE(+) = C.COD_LOCALIDADE
  AND G.COD_TIPO_LOGRADOURO(+) = C.TIP_LOGRADOURO
  AND F.COD_MOTIVO_SOLICITACAO = A.COD_MOTIVO_SOLICITACAO;
--------------------------------------------------------------------------------------------
SELECT *
 FROM SOLICITACAO_REL_MEDICO A
 WHERE A.COD_PACIENTE = '1188254B';
 
 SELECT *
  FROM PACIENTE C
  WHERE C.COD_PACIENTE = '1188254B';
  
select * from DOCUMENTO.RELATORIO_MEDICO t
where t.num_solic_rel_medico = 310509;
 
 
 
 
