SELECT P.CHAVE,
       P.PATRIMONIO_ATUAL,
       TP.DSC_TIPO_PATRIMONIO TIPO_PATRIMONIO,
        MT.COD_MATERIAL,
       MT.NOM_MATERIAL,
       BP.DSC_COMPLEMENTAR,
       P.PATRIMONIOS_POR_CHAVE,
       P.QTD,
       NVL(MT.TAX_DEPRECIACAO_ANUAL, SG.TAX_DEPRECIACAO_ANUAL) TAX_DEPRECIACAO_ANUAL,
       IC.DTA_HOR_INCORPORACAO,
       BP.DTA_DESINCORPORACAO,
       BP.CPL_LOCALIZACAO,
       IC.VLR_TOTAL_ITEM / NVL(IC.QTD_INCORPORADA, 1) VLR_BEM,
       NVL(CTA.COD_CONTABIL || ' - ' || CTA.DSC_CONTABIL, '') AS CONTA_CONTABIL,
       IC.DTA_INCORPORACAO_CONTABIL DATA_CONTABILIZACAO,
       BP.DTA_DESINCORPORACAO_CONTABIL
  FROM

       BEM_PATRIMONIAL              BP,
       INCORPORACAO                 IC,
       MATERIAL                     MT,
       TIPO_PATRIMONIO              TP,
       SUB_GRUPO                    SG,
       CONTA_CONTABIL               CTA,

    (SELECT  NP.NUM_BEM CHAVE,
               (SELECT A.NUM_PATRIMONIO
                 FROM BEM_PATRIMONIAL A WHERE A.NUM_BEM = NP.NUM_BEM) PATRIMONIO_ATUAL,

             (SELECT TP.DSC_TIPO_PATRIMONIO
                 FROM  TIPO_PATRIMONIO TP
                 WHERE TP.COD_TIPO_PATRIMONIO = BP.COD_TIPO_PATRIMONIO) TIPO_PATRIMONIO,

              RTRIM(XMLAGG(XMLELEMENT(E, NP.NUM_PATRIMONIO||'-'||TP.DSC_TIPO_PATRIMONIO, ',' || CHR(13)).EXTRACT('//text()') ORDER BY NP.NUM_PATRIMONIO)
                              .GETCLOBVAL(),  ',') PATRIMONIOS_POR_CHAVE,

           COUNT(*) QTD
    FROM NUMERO_PATRIMONIO NP
    LEFT JOIN BEM_PATRIMONIAL BP ON BP.NUM_BEM = NP.NUM_BEM
    JOIN TIPO_PATRIMONIO TP ON TP.COD_TIPO_PATRIMONIO = NP.COD_TIPO_PATRIMONIO
    GROUP BY NP.NUM_BEM, BP.COD_TIPO_PATRIMONIO ) P
 WHERE 1 = 1
   AND IC.NUM_INCORPORACAO =  BP.NUM_INCORPORACAO(+)
   AND MT.COD_MATERIAL = IC.COD_MATERIAL(+)
  AND BP.NUM_BEM = P.CHAVE(+)
   AND P.PATRIMONIO_ATUAL = BP.NUM_PATRIMONIO
   AND BP.COD_TIPO_PATRIMONIO = TP.COD_TIPO_PATRIMONIO(+)
   AND MT.COD_GRUPO = SG.COD_GRUPO(+)
   AND MT.COD_SUB_GRUPO = SG.COD_SUB_GRUPO(+)
   AND IC.COD_CONTA = CTA.COD_CONTA(+)
   AND IC.DTA_HOR_INCORPORACAO BETWEEN
       NVL(TO_DATE('01/04/1956', 'DD/MM/YYYY'), IC.DTA_HOR_INCORPORACAO) AND  NVL(TO_DATE('31/12/2020', 'DD/MM/YYYY'), IC.DTA_HOR_INCORPORACAO)
   AND bp.num_bem = 5400
 ORDER BY  NOM_MATERIAL, NUM_PATRIMONIO;
 ----------------------------------
 SELECT *
 FROM bem_patrimonial bp
 WHERE bp.num_patrimonio = 59999--10809
 AND bp.cod_tipo_patrimonio = 56;
 
 59999-HCRP
 64718
 57284
 58011
 10521-HCFMRP
 -----------------------------------
