----------------------------------------------------------------------
 -- Serviço externo
SELECT DISTINCT-- OS.NUM_ORDEM,                
                OS.NUM_ORDEM_SERVICO || '/' || OS.ANO_ORDEM_SERVICO NUM_OS,
                PAT.PATRIMONIO EQUIPAMENTO,
                PAT.DSC_COMPLEMENTAR,
                OS.DSC_SERVICO,
                OS.COD_CENCUSTO,
          --      TOS.COD_UNIDADE_EXECUTANTE,
                OS.DTA_CRIACAO_OS,
                DF.DTA_EMISSAO     DTA_OCORRENCIA,
                UE.NOM_UNIDADE_EXECUTANTE OFICINAS,

               -- 0 QTD_OS_CONCLUIDA,
               -- 0 QTD_HOR_APONT,
                DF.VLR_DOCUMENTO VLR_SERVICO_EXTERNO,
             --   0   VLR_MATERIAL,
                AGS.VLR_FATURADO,
              --  GC.COD_GRUPO,
                GC.DSC_GRUPO SOLICITANTE
             --   GC.ORD_IMPRESSAO

  FROM DOCUMENTO_FINANCEIRO        DF,
       AGENDA_AUT_ENTREGA_SERVICO  AGS,
       AUTORIZACAO_ENTREGA_SERVICO AES,
       COTACAO_PEDIDO_SERVICO      CPS,

       PEDIDO_SERVICO        PS,
       TRIAGEM_ORDEM_SERVICO TOS,
       ORDEM_SERVICO         OS,

       CENTRO_CUSTO   CC,
       GRUPO_CENCUSTO GC,

       (SELECT COD_UNIDADE_EXECUTANTE, NOM_UNIDADE_EXECUTANTE
          FROM UNIDADE_EXECUTANTE
         START WITH COD_UNIDADE_EXECUTANTE IN (2,5,6,7,8,9,11,22,70)
        CONNECT BY PRIOR COD_UNIDADE_EXECUTANTE = COD_UNIDADE_EXECUTANTE_PAI) UE,
        
        (SELECT    BP.NUM_BEM,
                   BP.DSC_COMPLEMENTAR,
             BP.NUM_PATRIMONIO||'-'||TP.DSC_TIPO_PATRIMONIO PATRIMONIO
    FROM BEM_PATRIMONIAL BP
    JOIN TIPO_PATRIMONIO TP
     ON TP.COD_TIPO_PATRIMONIO = BP.COD_TIPO_PATRIMONIO) PAT

 WHERE DF.DTA_HOR_LANCAMENTO BETWEEN TO_DATE('01/01/2015', 'DD/MM/YYYY') AND       TO_DATE('31/12/2020', 'DD/MM/YYYY')
   AND DF.NUM_DOC_FINANCEIRO = AGS.NUM_DOC_FINANCEIRO
   AND AGS.NUM_AUT_ENTREGA_SERVICO = AES.NUM_AUT_ENTREGA_SERVICO
   AND AES.NUM_COTACAO_SERVICO = CPS.NUM_COTACAO_SERVICO
   AND CPS.NUM_PEDIDO_SERVICO = PS.NUM_PEDIDO_SERVICO
   AND PS.NUM_TRIAGEM_OS = TOS.NUM_TRIAGEM_OS
   AND TOS.NUM_ORDEM = OS.NUM_ORDEM
   AND OS.COD_CENCUSTO = CC.COD_CENCUSTO
   AND CC.COD_GRUPO = GC.COD_GRUPO(+)
   AND TOS.COD_UNIDADE_EXECUTANTE = UE.COD_UNIDADE_EXECUTANTE
   AND OS.NUM_BEM = PAT.NUM_BEM(+)
   AND OS.COD_CENCUSTO IN ('CACK00013', 'CACN0001X', 'CACK00049', 'CACL00019','CACN04014')
   ORDER BY OS.DTA_CRIACAO_OS;
   
   
   (SELECT    BP.NUM_BEM,
             BP.NUM_PATRIMONIO||'-'||TP.DSC_TIPO_PATRIMONIO PATRIMONIO
    FROM BEM_PATRIMONIAL BP
    JOIN TIPO_PATRIMONIO TP
     ON TP.COD_TIPO_PATRIMONIO = BP.COD_TIPO_PATRIMONIO) PAT
    
