SELECT COD_ROLE PE,
       PE.NOM_ROLE,
       BLK_ACESSO_USR.USR,
       BLK_ACESSO_USR.BLOQUEADO
  FROM USUARIO_ROLE UR
  JOIN ACESSO.PERFIL PE
 USING (COD_ROLE)
  JOIN ACESSO.SISTEMA_PERFIL SP
 USING (COD_ROLE, COD_INST_SISTEMA)
  LEFT JOIN (SELECT PS.VLR_PADRAO,
                    PS.COD_INSTITUICAO,
                    REGEXP_SUBSTR(UPPER(PS.VLR_PARAMETRO), '[^|]+', 1, 1) AS USR,
                    REGEXP_SUBSTR(UPPER(PS.VLR_PARAMETRO), '[^|]+', 1, 2) AS BLOQUEADO
               FROM PARAMETRO_SISTEMA PS
              WHERE PS.COD_SISTEMA = 189
                AND PS.COD_MODULO = 2
                AND PS.VLR_PADRAO = 'RL_REPOSITORIO_FARMACIA') BLK_ACESSO_USR
    ON BLK_ACESSO_USR.VLR_PADRAO = NOM_ROLE
   AND BLK_ACESSO_USR.USR = UR.NUM_USER_BANCO
   AND BLK_ACESSO_USR.COD_INSTITUICAO = COD_INST_SISTEMA
 WHERE SP.COD_SISTEMA = 189
   AND COD_INST_SISTEMA = 1
   AND UR.NUM_USER_BANCO = FC_NUM_USER_BANCO
GROUP BY COD_ROLE, PE.NOM_ROLE, BLK_ACESSO_USR.USR, BLK_ACESSO_USR.BLOQUEADO;
