SELECT *
 FROM INSTITUICAO_ESPECIE_DOCUMENTO i
 WHERE i.cod_instituicao = 2;
 
SELECT *
 FROM SEQUENCES_HCRP s;
 
 SELECT *
  FROM MODALIDADE_LICIT_INSTITUICAO;
 
 SEQ_NUM_ARQUIVO_GERAL_FAEPA;
 --SEQ_NUM_SPSEMPAPEL_HC
 select *
from   dba_sequences d
where  d.sequence_name = 'SEQ_NUM_ARQUIVO_GERAL_FAEPA';

PROC_VOLTA_SEQUENCES;

SELECT *
FROM SEQ_ERRO_VOLTA s
WHERE s.sequence_name = 'SEQ_NUM_ARQUIVO_GERAL_FAEPA';


SELECT *
 FROM dba_synonyms d
 WHERE d.SYNONYM_NAME = 'SEQ_NUM_ARQUIVO_GERAL_FAEPA';
 --'SEQ_NUM_ARQUIVO_GERAL_FAEPA';

