SELECT COD_INSTITUICAO, DSC_ESTRUTURA, COD_ESTRUTURA 
FROM ESTRUTURA_ORCAMENTARIA E 
WHERE E.COD_ESTRUTURA = 
AND E.COD_INSTITUICAO = 
SELECT MAX(TOS.NUM_TRIAGEM_OS) ULTIMA_TRIAGEM 
  FROM ORDEM_SERVICO         OS 
 ,TRIAGEM_ORDEM_SERVICO TOS 
 ,UNIDADE_EXECUTANTE    UE 
 WHERE OS.NUM_ORDEM = TOS.NUM_ORDEM 
 AND TOS.COD_UNIDADE_EXECUTANTE = UE.COD_UNIDADE_EXECUTANTE 
 AND UE.COD_UNIDADE_EXECUTANTE_PAI = 
 AND OS.NUM_ORDEM_SERVICO = 
 AND OS.ANO_ORDEM_SERVICO = 

 SELECT SEQ_AUT_ENTREGA_HC.NEXTVAL AS ID FROM DUAL
 SELECT SEQ_AUT_ENTREGA_FAEPA.NEXTVAL AS ID FROM DUAL

 SELECT SEQ_PEDIDO_SERVICO.CURRVAL AS ID FROM DUAL

 SELECT SEQ_COTACAO_ITEM_OS.CURRVAL AS ID FROM DUAL
 
SELECT NUM_AUTORIZACAO_ENTREGA, ANO_AUTORIZACAO_ENTREGA, COD_INSTITUICAO FROM (SELECT NUM_AUTORIZACAO_ENTREGA , ANO_AUTORIZACAO_ENTREGA, COD_INSTITUICAO FROM AUTORIZACAO_ENTREGA ORDER BY DTA_EMISSAO desc) 

 SELECT * FROM (SELECT NUM_AUT_ENTREGA_SERVICO FROM AUTORIZACAO_ENTREGA_SERVICO ORDER BY NUM_AUT_ENTREGA_SERVICO DESC) WHERE ROWNUM = 1 


--Insert em AGENDA_AUT_ENTREGA_SERVICO
--Insert em ONERACAO_AUT_ENTREGA_SERVICO
