SELECT * FROM (WITH SOLICITACOES_DO_DIA AS  
   (SELECT DISTINCT * FROM (SELECT A.*  
      FROM TRANSPORTE_MATERIAL A  
     WHERE A.IDF_ATENDIMENTO = 0
       AND TRUNC(A.DTA_HOR_SOLICITACAO) = TRUNC(SYSDATE)  
       AND TRUNC(A.DTA_HOR_AGENDADO) > TRUNC(TO_DATE('01/01/2021', 'DD/MM/YYYY'))  
       AND TRUNC(A.DTA_HOR_CANCELADO) = TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))  
    UNION ALL  
    SELECT A.*  
      FROM TRANSPORTE_MATERIAL A  
     WHERE A.IDF_ATENDIMENTO = 0
       AND TRUNC(A.DTA_HOR_AGENDADO) = TRUNC(SYSDATE)  
       AND TRUNC(A.DTA_HOR_CANCELADO) = TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))))  
  SELECT   
       (SELECT TRUNC(SYSDATE) FROM DUAL) DATA_ATUAL,  
       (SELECT COUNT(*) FROM SOLICITACOES_DO_DIA ) TOTAL_SOLICITACOES_DIA,   
       (SELECT COUNT(*) FROM SOLICITACOES_DO_DIA WHERE TRUNC(DTA_HOR_INICIO) = TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY')) AND TRUNC(DTA_HOR_FIM) = TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))) TOTAL_NAO_FINALIZADOS,  
       (SELECT COUNT(*) FROM SOLICITACOES_DO_DIA WHERE TRUNC(DTA_HOR_INICIO) > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY')) AND TRUNC(DTA_HOR_FIM) = TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))) TOTAL_EM_ATENDIMENTO,  
       (SELECT COUNT(*) FROM SOLICITACOES_DO_DIA WHERE TRUNC(DTA_HOR_INICIO) > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY')) AND TRUNC(DTA_HOR_FIM) > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))) TOTAL_FINALIZADOS,  
       (SELECT COUNT(*) FROM SOLICITACOES_DO_DIA WHERE IDF_TRANSPORTE IN (0)) TOTAL_URGENCIAS,  
       (SELECT COUNT(*) FROM SOLICITACOES_DO_DIA WHERE IDF_TRANSPORTE NOT IN (0)) TOTAL_NAO_URGENCIAS,  
       (SELECT COUNT(*) FROM USUARIO A, USUARIO_ATENDE B WHERE A.NUM_USER_BANCO = B.NUM_USER_BANCO AND NVL(A.DTA_EXPIRACAO, SYSDATE) >= SYSDATE AND B.IDF_ATENDIMENTO = 0 AND (SELECT COUNT(*) CPF FROM R034FUN R WHERE LPAD(R.NUMCPF, 11, '0') = LPAD(A.NUM_DOCUMENTO, 11, '0') AND ROWNUM = 1 AND R.SITAFA IN (SELECT S.CODSIT FROM R010SIT S WHERE S.TIPSIT = 1)) > 0) NUMERO_FUNCIONARIOS, 
       (SELECT TRUNC((SELECT COUNT(*) FROM SOLICITACOES_DO_DIA) / (SELECT DECODE(COUNT(*), 0, 1,COUNT(*)) FROM USUARIO A, USUARIO_ATENDE B WHERE A.NUM_USER_BANCO = B.NUM_USER_BANCO AND NVL(A.DTA_EXPIRACAO, SYSDATE) >= SYSDATE AND B.IDF_ATENDIMENTO = 0 AND (SELECT COUNT(*) CPF FROM R034FUN R WHERE LPAD(R.NUMCPF, 11, '0') = LPAD(A.NUM_DOCUMENTO, 11, '0') AND ROWNUM = 1 AND R.SITAFA IN (SELECT S.CODSIT FROM R010SIT S WHERE S.TIPSIT = 1)) > 0), 2) FROM DUAL) MEDIA_SOLICITACOES_POR_FUNC, 
       (SELECT TRUNC((AVG((DTA_HOR_FIM-DTA_HOR_INICIO)* 24 * 60))) FROM SOLICITACOES_DO_DIA WHERE DTA_HOR_INICIO > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY')) AND TRUNC(DTA_HOR_FIM) > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))) MEDIA_ATENDIMENTO_SOLIC_EM_MIN,  
       (SELECT TRUNC(MAX((DTA_HOR_FIM-DTA_HOR_INICIO)* 24 * 60)) FROM SOLICITACOES_DO_DIA WHERE DTA_HOR_INICIO > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY')) AND TRUNC(DTA_HOR_FIM) > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))) MAIOR_TEMPO_ATENDIMENTO_EM_MIN,  
       (SELECT TRUNC(MIN((DTA_HOR_FIM-DTA_HOR_INICIO)* 24 * 60)) FROM SOLICITACOES_DO_DIA WHERE DTA_HOR_INICIO > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY')) AND TRUNC(DTA_HOR_FIM) > TRUNC(TO_DATE('01/01/1800', 'DD/MM/YYYY'))) MENOR_TEMPO_ATENDIMENTO_EM_MIN  
  FROM DUAL);
  
  
SELECT *
 FROM TRANSPORTE_MATERIAL tm
 WHERE tm.dta_hor_solicitacao > TRUNC(SYSDATE);
