SELECT TP.COD_TIPO_PATRIMONIO,
       TP.DSC_TIPO_PATRIMONIO

FROM TIPO_PATRIMONIO TP
  INNER JOIN USUARIO_TIPO_PATRIMONIO UTP ON UTP.COD_TIPO_PATRIMONIO = TP.COD_TIPO_PATRIMONIO
      AND UTP.NUM_USER_BANCO = 66827
  INNER JOIN INSTITUICAO_TIPO_PATRIMONIO ITP ON ITP.COD_TIPO_PATRIMONIO = TP.COD_TIPO_PATRIMONIO
      AND ITP.COD_INST_SISTEMA = 1
ORDER BY TP.DSC_TIPO_PATRIMONIO;
--71587

SELECT *
 FROM usuario u
 WHERE u.nom_usuario_banco = 'ASYRODRIGUES';
