prompt Importing table USUARIO_TIPO_PATRIMONIO...
set feedback off
set define off

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 1);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 2);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 3);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 4);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 5);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 6);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 7);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 8);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 9);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 10);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 11);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 12);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 13);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 14);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 15);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 16);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 17);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 18);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 19);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 20);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 21);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 22);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 23);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 24);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 25);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 26);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 27);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 28);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 29);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 30);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 31);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 32);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 33);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 34);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 35);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 37);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 38);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 39);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 40);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 41);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 42);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 43);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 44);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 45);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 46);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 47);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 48);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 49);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 50);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 51);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 56);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 57);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 58);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 59);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 60);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 266);

insert into USUARIO_TIPO_PATRIMONIO (NUM_USER_BANCO, COD_TIPO_PATRIMONIO)
values (66827, 418);

prompt Done.
