
insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA00019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('AAAA00017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('AAAA00029', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('BAAA0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00024', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00048', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA0005X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00061', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00073', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00085', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00097', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00103', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00139', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00140', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00152', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00164', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00176', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00188', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA0019X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00206', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00218', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA0022X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00231', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00243', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00255', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00267', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00279', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CAAA00280', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABA00045', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABA01013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABA02017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABA02029', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABB00015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABC00010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABD00016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABD0003X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABE00011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABF00017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABF00029', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABG00012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABH00018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABH00055', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABH00511', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABI00025', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABI00037', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABJ00010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABK00016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABL00011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABN00012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABN00036', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABN00048', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABS0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABS00021', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABS00057', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABS00069', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABS00070', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABT00017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABT00029', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABT00030', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABU00012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CABU00024', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACA00017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC0002X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00043', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00055', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00080', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00109', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00146', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00158', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC0016X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00183', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00213', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00249', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00262', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00274', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00286', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00298', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00316', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC0050X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00511', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC00523', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC01011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC01035', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC03019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC03032', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC04012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC04036', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC05016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC05028', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC0601X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC06033', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC06057', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC07013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC07037', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC07049', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC07050', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACC08029', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACD02010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACD02022', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACD02034', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACD02046', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACE01012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACE0203X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACE02041', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACE0301X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACE04013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACE04049', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACF01018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACF0102X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACF03015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACF03039', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACG01013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACG03010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACG04014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACG04063', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACG05018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACG05031', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACH01019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACH04021', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACI01014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACI03011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACJ00018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACJ01011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACJ03019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACJ04012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK00013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK00049', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK00062', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK00074', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK00086', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK00098', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK02010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACK03014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACL00019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACL00020', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACM01018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACM01031', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACM02011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACM02035', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACM02059', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACM03015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACM03039', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACN0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACN00033', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACN01013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACN01037', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACN01050', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACN03010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACN04014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO00027', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO00040', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO00064', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO01019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO02012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO03016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO03053', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO0401X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACO04100', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACP01014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACP01038', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACQ00016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACQ00028', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACQ0003X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACQ03017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACR00011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACR00023', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CACR00035', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CADA00014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CADA00026', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAA00011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAA00059', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAA00060', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAA01015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAC00012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAC00048', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAC0103X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAD00018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAD0002X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBAD00031', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBBA02016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBBD00015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBBE00010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CBCA00016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCAA00010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCAA00022', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCAA00046', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCAA00058', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCAA0006X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCAA00071', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCAA00083', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCEA0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCEB00015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCEB00027', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CCEB00039', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CDAA0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA00019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA00020', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA00032', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA00068', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA0007X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA00081', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA00093', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA0010X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA00111', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA01024', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAA02016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAB01018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAB0102X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAB01031', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAB02011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAB02023', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAB02059', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAB03015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAC0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAD00027', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAE00010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAF00028', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAG00011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEAH00017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECB00019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECB00044', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECB01024', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECB03021', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECB03033', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECB03045', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC01018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC02011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC02035', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC02047', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC03015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04032', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04044', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04056', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04068', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC0407X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04081', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04093', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC0410X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04214', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC04226', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CECC05012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEDB00016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEDB00041', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEDB03017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEDB03030', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEDB03042', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CEDC00011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFAB00013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFAB00037', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFAB05011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFAC00019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFAC05017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFAD00014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00024', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00036', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00048', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA0005X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00061', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00073', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00115', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00127', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCA00139', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCB00018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC00025', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC00049', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC00062', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC00074', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC00086', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC00098', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC02010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFCC02022', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFDA0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFDA00021', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFDB00015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFDB06017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFDC05019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CFDC06036', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGAA00042', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGAB00012', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGCA00011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGCB00017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGCC0201X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA00032', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA00044', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA00056', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA00068', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA02016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA02028', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA0301X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDA03021', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDC0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDC00021', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGDC00033', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEA00016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEA00028', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEA0101X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEA02013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEC00017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEC00029', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEC02014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGED03013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGED04017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEE00018', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEE01011', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEE01023', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGEE01035', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFA00013', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFA00128', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFA01017', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFB00019', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFB00020', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFC00014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFC0102X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFD0001X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFD00021', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CGFD04014', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CHAA00016', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CHAA00028', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('CHAB00023', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00015', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00027', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00040', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00052', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00064', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00076', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00088', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA0009X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00106', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00118', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA0012X', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00143', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00155', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00179', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAA00180', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAB00010', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAB00022', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAB00034', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('DAAB00058', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('HEAB00186', 58127, 2, 'N');

insert into CENTRO_CUSTO_USUARIO (COD_CENCUSTO, NUM_USER_BANCO, IDF_RESPONSABILIDADE, IDF_NOTIFICACAO_CONSUMO)
values ('MATER0072', 58127, 2, 'N');


